#!/usr/bin/env bash
#
# apply-chrome-theme.sh — Apply GM3 BrowserThemeColor to Chromium-based browsers
#
# Usage:
#   apply-chrome-theme.sh                  # auto-detect color from material pipeline
#   apply-chrome-theme.sh "#ff6b35"        # explicit hex color
#
# Supports: Google Chrome, Chromium, Brave
# Requires: jq, writable policy dir (one-time sudo setup)
#
# One-time setup per browser:
#   sudo mkdir -p /etc/chromium/policies/managed && sudo chown "$USER" /etc/chromium/policies/managed
#   sudo mkdir -p /etc/opt/chrome/policies/managed && sudo chown "$USER" /etc/opt/chrome/policies/managed
#   sudo mkdir -p /etc/brave/policies/managed && sudo chown "$USER" /etc/brave/policies/managed

XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
STATE_DIR="$XDG_STATE_HOME/quickshell"
LOG_FILE="$STATE_DIR/user/generated/chrome_theme.log"
mkdir -p "$STATE_DIR/user/generated" 2>/dev/null
: > "$LOG_FILE" 2>/dev/null

log() { echo "[chrome] $*" >> "$LOG_FILE"; }

# ── Resolve theme color ─────────────────────────────────────────────────────

resolve_color() {
  # 1. Explicit argument
  if [[ -n "$1" && "$1" =~ ^#[A-Fa-f0-9]{6}$ ]]; then
    echo "$1"
    return
  fi

  # 2. colors.json (matugen output)
  local colors_json="$STATE_DIR/user/generated/colors.json"
  if [[ -f "$colors_json" ]] && command -v jq &>/dev/null; then
    local c
    c=$(jq -r '.primary // empty' "$colors_json" 2>/dev/null)
    if [[ -n "$c" ]]; then
      echo "$c"
      return
    fi
  fi

  # 3. material_colors.scss fallback
  local scss_file="$STATE_DIR/user/generated/material_colors.scss"
  if [[ -f "$scss_file" ]]; then
    local c
    c=$(grep '^\$primary:' "$scss_file" | sed 's/.*: *\(#[A-Fa-f0-9]\{6\}\).*/\1/')
    if [[ -n "$c" ]]; then
      echo "$c"
      return
    fi
  fi
}

# ── Resolve dark/light mode ─────────────────────────────────────────────────
# Returns Chrome's color_scheme2 value:
#   2 = dark, 1 = light
# Reads $darkmode from material_colors.scss (set by generate_colors_material.py)

resolve_color_scheme() {
  local scss_file="$STATE_DIR/user/generated/material_colors.scss"
  if [[ -f "$scss_file" ]]; then
    local val
    val=$(grep '^\$darkmode:' "$scss_file" | sed 's/.*: *\(.*\);/\1/' | tr -d ' ')
    if [[ "$val" == "True" || "$val" == "true" ]]; then
      echo 2  # dark
      return
    fi
  fi
  echo 1  # light
}

# ── Browser registry ─────────────────────────────────────────────────────────
# Each entry: bin_name|policy_dir|prefs_dir

BROWSERS=()

_register() {
  local bin="$1" policy_dir="$2" prefs_dir="$3"
  if command -v "$bin" &>/dev/null; then
    BROWSERS+=("$bin|$policy_dir|$prefs_dir")
  fi
}

# Google Chrome
_register google-chrome-stable "/etc/opt/chrome/policies/managed" "$HOME/.config/google-chrome"
_register google-chrome        "/etc/opt/chrome/policies/managed" "$HOME/.config/google-chrome"
# Chromium
_register chromium             "/etc/chromium/policies/managed"   "$HOME/.config/chromium"
_register chromium-browser     "/etc/chromium/policies/managed"   "$HOME/.config/chromium"
# Brave
_register brave                "/etc/brave/policies/managed"      "$HOME/.config/BraveSoftware/Brave-Browser"
_register brave-browser        "/etc/brave/policies/managed"      "$HOME/.config/BraveSoftware/Brave-Browser"

# Deduplicate by policy_dir (e.g. google-chrome-stable vs google-chrome)
_dedup_browsers() {
  local -A seen
  local deduped=()
  for entry in "${BROWSERS[@]}"; do
    local policy_dir="${entry#*|}"
    policy_dir="${policy_dir%%|*}"
    if [[ -z "${seen[$policy_dir]:-}" ]]; then
      seen[$policy_dir]=1
      deduped+=("$entry")
    fi
  done
  BROWSERS=("${deduped[@]}")
}

# ── Preferences fixer ────────────────────────────────────────────────────────
# Ensures browser Preferences are set so managed policy theme takes effect.
# Clears user themes, sets color_scheme2 explicitly to dark (2) or light (1).
# On Niri/Quickshell there is no GNOME portal — Chrome cannot auto-detect
# system dark/light, so we must set it directly every run.

fix_preferences() {
  local prefs_dir="$1"
  local name="$2"
  local cs2="$3"  # color_scheme2: 2=dark, 1=light
  local prefs_file="$prefs_dir/Default/Preferences"

  # Create Default dir and minimal Preferences if missing
  if [[ ! -f "$prefs_file" ]]; then
    mkdir -p "$prefs_dir/Default" 2>/dev/null
    echo '{}' > "$prefs_file"
    log "$name: created empty Preferences file"
  fi

  # Apply all required defaults via jq — every run, not cached
  # extensions.theme.id = ""           → clear any installed/autogenerated theme
  # extensions.theme.use_system = false → don't use system theme
  # extensions.theme.use_custom = false → don't use custom theme
  # browser.theme.color_scheme = 2     → follow device (legacy key)
  # browser.theme.user_color = 2       → follow device (legacy key)
  # browser.theme.color_scheme2        → 2=dark, 1=light (explicit, no portal needed)
  local tmp_file="${prefs_file}.ii-tmp"

  if jq --argjson cs2 "$cs2" '
    .extensions.theme.id = "" |
    .extensions.theme.use_system = false |
    .extensions.theme.use_custom = false |
    .browser.theme.color_scheme = 2 |
    .browser.theme.user_color = 2 |
    .browser.theme.color_scheme2 = $cs2
  ' "$prefs_file" > "$tmp_file" 2>/dev/null && [[ -s "$tmp_file" ]]; then
    mv "$tmp_file" "$prefs_file"
    log "$name: preferences set (color_scheme2=$cs2)"
  else
    rm -f "$tmp_file"
    log "$name: ERROR — failed to update preferences"
  fi
}

# ── Write policy and refresh ─────────────────────────────────────────────────

apply_to_browser() {
  local bin="$1"
  local policy_dir="$2"
  local prefs_dir="$3"
  local theme_color="$4"
  local cs2="$5"  # color_scheme2: 2=dark, 1=light
  local name="$bin"

  # Fix preferences first — sets dark/light explicitly since no portal on Niri
  fix_preferences "$prefs_dir" "$name" "$cs2"

  # Check policy dir
  if [[ ! -d "$policy_dir" || ! -w "$policy_dir" ]]; then
    log "$name: policy dir not writable → sudo mkdir -p $policy_dir && sudo chown \$USER $policy_dir"
    return
  fi

  # Write policy — only BrowserThemeColor
  echo "{\"BrowserThemeColor\": \"$theme_color\"}" | tee "$policy_dir/ii-theme.json" >/dev/null

  # Refresh running instance
  "$bin" --refresh-platform-policy --no-startup-window >/dev/null 2>&1 & disown
  log "$name: applied theme $theme_color (color_scheme2=$cs2)"
}

# ── Main ─────────────────────────────────────────────────────────────────────

main() {
  local theme_color
  theme_color=$(resolve_color "$1")

  if [[ -z "$theme_color" ]]; then
    log "Could not determine primary color. Skipping."
    return 1
  fi

  local cs2
  cs2=$(resolve_color_scheme)

  log "GM3 seed color: $theme_color, mode: $([ "$cs2" = 2 ] && echo dark || echo light)"

  _dedup_browsers

  if [[ ${#BROWSERS[@]} -eq 0 ]]; then
    log "No Chromium-based browsers found. Skipping."
    return 0
  fi

  for entry in "${BROWSERS[@]}"; do
    IFS='|' read -r bin policy_dir prefs_dir <<< "$entry"
    apply_to_browser "$bin" "$policy_dir" "$prefs_dir" "$theme_color" "$cs2"
  done
}

main "$@"
