#!/usr/bin/env python3
"""
Generate terminal color configuration files from material_colors.scss
Supports: Kitty, Alacritty, Foot, WezTerm, Ghostty, Konsole
Auto-integrates into existing terminal configs
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path


def parse_scss_colors(scss_path):
    """Parse material_colors.scss and extract color variables"""
    colors = {}
    try:
        with open(scss_path, "r") as f:
            for line in f:
                # Match lines like: $term0: #282828;
                match = re.match(r"\$(\w+):\s*(#[A-Fa-f0-9]{6});", line.strip())
                if match:
                    name, value = match.groups()
                    colors[name] = value
    except FileNotFoundError:
        print(f"Error: Could not find {scss_path}", file=sys.stderr)
        sys.exit(1)
    return colors


def ensure_line_in_file(filepath, line_to_add, check_pattern=None, at_top=False):
    """Add a line to a file if it doesn't exist. Creates file if needed."""
    filepath = Path(filepath)
    filepath.parent.mkdir(parents=True, exist_ok=True)

    # Check if file exists and if line already present
    if filepath.exists():
        content = filepath.read_text()
        if check_pattern:
            if re.search(check_pattern, content):
                return False  # Already present
        elif line_to_add in content:
            return False  # Already present
    else:
        content = ""

    # Add line
    if at_top:
        # Add at the beginning of file
        content = line_to_add + "\n" + content
    else:
        # Add at the end
        if content and not content.endswith("\n"):
            content += "\n"
        content += line_to_add + "\n"

    filepath.write_text(content)
    return True  # Added


def generate_kitty_config(colors, output_path):
    """Generate Kitty terminal color config and auto-integrate"""
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

# The basic colors
foreground              {colors.get("term7", "#A89984")}
background              {colors.get("term0", "#282828")}
selection_foreground    {colors.get("term0", "#282828")}
selection_background    {colors.get("term7", "#A89984")}

# Cursor colors
cursor                  {colors.get("term7", "#A89984")}
cursor_text_color       {colors.get("term0", "#282828")}

# URL underline color when hovering with mouse
url_color               {colors.get("term4", "#458588")}

# Kitty window border colors
active_border_color     {colors.get("primary", "#458588")}
inactive_border_color   {colors.get("term8", "#928374")}
bell_border_color       {colors.get("term1", "#CC241D")}

# Tab bar colors
active_tab_foreground   {colors.get("onPrimary", "#FFFFFF")}
active_tab_background   {colors.get("primary", "#458588")}
inactive_tab_foreground {colors.get("term7", "#A89984")}
inactive_tab_background {colors.get("term8", "#928374")}
tab_bar_background      {colors.get("term0", "#282828")}

# The 16 terminal colors

# black
color0 {colors.get("term0", "#282828")}
color8 {colors.get("term8", "#928374")}

# red
color1 {colors.get("term1", "#CC241D")}
color9 {colors.get("term9", "#FB4934")}

# green
color2  {colors.get("term2", "#98971A")}
color10 {colors.get("term10", "#B8BB26")}

# yellow
color3  {colors.get("term3", "#D79921")}
color11 {colors.get("term11", "#FABD2F")}

# blue
color4  {colors.get("term4", "#458588")}
color12 {colors.get("term12", "#83A598")}

# magenta
color5  {colors.get("term5", "#B16286")}
color13 {colors.get("term13", "#D3869B")}

# cyan
color6  {colors.get("term6", "#689D6A")}
color14 {colors.get("term14", "#8EC07C")}

# white
color7  {colors.get("term7", "#A89984")}
color15 {colors.get("term15", "#EBDBB2")}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into kitty.conf
    home = os.path.expanduser("~")
    kitty_conf = f"{home}/.config/kitty/kitty.conf"
    if ensure_line_in_file(
        kitty_conf, "include current-theme.conf", r"include\s+current-theme\.conf"
    ):
        print(f"✓ Generated Kitty config and auto-integrated")
    else:
        print(f"✓ Generated Kitty config (already integrated)")

    # Live reload kitty colors via remote control socket
    import subprocess

    socket_path = "/tmp/kitty-socket"
    if os.path.exists(socket_path):
        try:
            subprocess.run(
                [
                    "kitten",
                    "@",
                    "--to",
                    f"unix:{socket_path}",
                    "set-colors",
                    "--all",
                    output_path,
                ],
                capture_output=True,
                timeout=2,
            )
            print(f"  → Live-reloaded Kitty colors via socket")
        except Exception:
            pass


def fix_alacritty_import_order(config_path):
    """
    Fix alacritty.toml to use [general] import (Alacritty 0.15+) at the top
    and comment out hardcoded colors. Creates backup before modifying.
    Returns: (modified: bool, message: str)
    """
    try:
        with open(config_path, "r") as f:
            content = f.read()
    except FileNotFoundError:
        return False, "Config file not found"
    except PermissionError:
        return False, "Permission denied"

    import_line = 'import = ["~/.config/alacritty/colors.toml"]'
    bare_import_pat = r"^import\s*=\s*\[.*?colors\.toml.*?\]"
    general_import_pat = r"import\s*=\s*\[.*?colors\.toml.*?\]"

    has_hardcoded_colors = bool(
        re.search(r"^\[colors\.(primary|normal|bright)\]", content, re.MULTILINE)
    )

    # Check if [general] with import is already at the top (correct state)
    lines = content.split("\n")
    top_lines = [
        l.strip() for l in lines[:10] if l.strip() and not l.strip().startswith("#")
    ]

    # Correct state: [general] is first real line, import is second, no hardcoded colors
    correct = (
        len(top_lines) >= 2
        and top_lines[0] == "[general]"
        and bool(re.match(general_import_pat, top_lines[1]))
        and not has_hardcoded_colors
    )
    if correct:
        return False, "Config is already correct"

    # Create backup
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = f"{config_path}.backup_{timestamp}"
    try:
        Path(backup_path).write_text(content)
    except Exception as e:
        return False, f"Failed to create backup: {e}"

    # Build new content: [general] with import at top, then rest of config
    new_lines = [
        "# iNiR wallpaper theming - import must be at top to override colors",
        "[general]",
        import_line,
    ]

    in_general = False
    in_colors_section = False
    added_colors_comment = False

    for line in lines:
        stripped = line.strip()

        # Skip old bare import lines and their iNiR comments
        if re.match(bare_import_pat, stripped):
            continue
        if stripped.startswith("# iNiR wallpaper theming"):
            continue

        # Handle existing [general] section - absorb its non-import content
        if stripped == "[general]":
            in_general = True
            continue
        if in_general:
            if stripped.startswith("[") and stripped != "[general]":
                in_general = False
                # Fall through to process this line normally
            elif re.match(general_import_pat, stripped):
                continue  # Skip - we already added import at top
            elif stripped:
                # Move other [general] settings (live_config_reload, etc.) to top
                new_lines.append(stripped)
                continue
            else:
                continue  # Skip empty lines in old [general]

        # Comment out hardcoded color sections
        if re.match(r"^\[colors\.(primary|normal|bright|cursor|selection)\]", stripped):
            if not added_colors_comment:
                in_colors_section = True
                added_colors_comment = True
                new_lines.append("")
                new_lines.append(
                    "# Color definitions commented out by iNiR wallpaper theming"
                )
                new_lines.append(
                    "# Colors are managed via the import in [general] above"
                )
                new_lines.append("#")
            new_lines.append("# " + line)
            continue

        if in_colors_section:
            if stripped.startswith("[") and not stripped.startswith("[colors"):
                in_colors_section = False
                new_lines.append("")
                new_lines.append(line)
            elif stripped and "=" in stripped:
                new_lines.append("# " + line)
            else:
                new_lines.append("# " + line if stripped else "")
            continue

        new_lines.append(line)

    try:
        Path(config_path).write_text("\n".join(new_lines))
    except Exception as e:
        Path(config_path).write_text(content)
        return False, f"Failed to write config: {e}"

    return True, f"Fixed config (backup: {backup_path})"


def generate_alacritty_config(colors, output_path):
    """Generate Alacritty terminal color config and auto-integrate"""
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

[colors.primary]
background = '{colors.get("term0", "#282828")}'
foreground = '{colors.get("term7", "#A89984")}'

[colors.cursor]
text   = '{colors.get("term0", "#282828")}'
cursor = '{colors.get("term7", "#A89984")}'

[colors.selection]
text       = '{colors.get("term0", "#282828")}'
background = '{colors.get("term7", "#A89984")}'

[colors.normal]
black   = '{colors.get("term0", "#282828")}'
red     = '{colors.get("term1", "#CC241D")}'
green   = '{colors.get("term2", "#98971A")}'
yellow  = '{colors.get("term3", "#D79921")}'
blue    = '{colors.get("term4", "#458588")}'
magenta = '{colors.get("term5", "#B16286")}'
cyan    = '{colors.get("term6", "#689D6A")}'
white   = '{colors.get("term7", "#A89984")}'

[colors.bright]
black   = '{colors.get("term8", "#928374")}'
red     = '{colors.get("term9", "#FB4934")}'
green   = '{colors.get("term10", "#B8BB26")}'
yellow  = '{colors.get("term11", "#FABD2F")}'
blue    = '{colors.get("term12", "#83A598")}'
magenta = '{colors.get("term13", "#D3869B")}'
cyan    = '{colors.get("term14", "#8EC07C")}'
white   = '{colors.get("term15", "#EBDBB2")}'
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into alacritty.toml and fix import order
    home = os.path.expanduser("~")
    alacritty_conf = f"{home}/.config/alacritty/alacritty.toml"

    # Fix import order and migrate to [general] import (Alacritty 0.15+)
    if os.path.exists(alacritty_conf):
        modified, message = fix_alacritty_import_order(alacritty_conf)
        if modified:
            print(f"✓ Generated Alacritty config ({message})")
        else:
            print(f"✓ Generated Alacritty config ({message})")
    else:
        # Create new config with [general] import at top
        new_conf = (
            "# iNiR wallpaper theming\n"
            "[general]\n"
            'import = ["~/.config/alacritty/colors.toml"]\n'
        )
        Path(alacritty_conf).parent.mkdir(parents=True, exist_ok=True)
        Path(alacritty_conf).write_text(new_conf)
        print(f"✓ Generated Alacritty config and created new config file")


def generate_foot_config(colors, output_path):
    """Generate Foot terminal color config and auto-integrate"""
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

[colors]
foreground={colors.get("term7", "#A89984")[1:]}
background={colors.get("term0", "#282828")[1:]}

## Normal/regular colors (color palette 0-7)
regular0={colors.get("term0", "#282828")[1:]}  # black
regular1={colors.get("term1", "#CC241D")[1:]}  # red
regular2={colors.get("term2", "#98971A")[1:]}  # green
regular3={colors.get("term3", "#D79921")[1:]}  # yellow
regular4={colors.get("term4", "#458588")[1:]}  # blue
regular5={colors.get("term5", "#B16286")[1:]}  # magenta
regular6={colors.get("term6", "#689D6A")[1:]}  # cyan
regular7={colors.get("term7", "#A89984")[1:]}  # white

## Bright colors (color palette 8-15)
bright0={colors.get("term8", "#928374")[1:]}   # bright black
bright1={colors.get("term9", "#FB4934")[1:]}   # bright red
bright2={colors.get("term10", "#B8BB26")[1:]}  # bright green
bright3={colors.get("term11", "#FABD2F")[1:]}  # bright yellow
bright4={colors.get("term12", "#83A598")[1:]}  # bright blue
bright5={colors.get("term13", "#D3869B")[1:]}  # bright magenta
bright6={colors.get("term14", "#8EC07C")[1:]}  # bright cyan
bright7={colors.get("term15", "#EBDBB2")[1:]}  # bright white

## Cursor and selection colors
selection-foreground={colors.get("term0", "#282828")[1:]}
selection-background={colors.get("term7", "#A89984")[1:]}
jump-labels={colors.get("term0", "#282828")[1:]} {colors.get("term3", "#D79921")[1:]}
urls={colors.get("term4", "#458588")[1:]}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into foot.ini (add at the top to avoid section issues)
    home = os.path.expanduser("~")
    foot_conf = f"{home}/.config/foot/foot.ini"
    if ensure_line_in_file(
        foot_conf,
        "include=~/.config/foot/colors.ini",
        r"include\s*=.*colors\.ini",
        at_top=True,
    ):
        print(f"✓ Generated Foot config and auto-integrated")
    else:
        print(f"✓ Generated Foot config (already integrated)")

    # Remove stale colors.ini include (legacy from old matugen terminal template,
    # no longer updated — was overriding inir-colors.ini with stale colors)
    foot_path = Path(foot_conf)
    if foot_path.exists():
        old_content = foot_path.read_text()
        new_content = re.sub(
            r"^include\s*=\s*~/.config/foot/colors\.ini\s*\n?",
            "",
            old_content,
            flags=re.MULTILINE,
        )
        if new_content != old_content:
            foot_path.write_text(new_content)


def generate_wezterm_config(colors, output_path):
    """Generate WezTerm terminal color config and auto-integrate"""
    config = f"""-- Auto-generated by ii wallpaper theming system
-- Do not edit manually - changes will be overwritten

return {{
  foreground = '{colors.get("term7", "#A89984")}',
  background = '{colors.get("term0", "#282828")}',

  cursor_bg = '{colors.get("term7", "#A89984")}',
  cursor_fg = '{colors.get("term0", "#282828")}',
  cursor_border = '{colors.get("term7", "#A89984")}',

  selection_fg = '{colors.get("term0", "#282828")}',
  selection_bg = '{colors.get("term7", "#A89984")}',

  scrollbar_thumb = '{colors.get("term8", "#928374")}',
  split = '{colors.get("term8", "#928374")}',

  ansi = {{
    '{colors.get("term0", "#282828")}',  -- black
    '{colors.get("term1", "#CC241D")}',  -- red
    '{colors.get("term2", "#98971A")}',  -- green
    '{colors.get("term3", "#D79921")}',  -- yellow
    '{colors.get("term4", "#458588")}',  -- blue
    '{colors.get("term5", "#B16286")}',  -- magenta
    '{colors.get("term6", "#689D6A")}',  -- cyan
    '{colors.get("term7", "#A89984")}',  -- white
  }},

  brights = {{
    '{colors.get("term8", "#928374")}',  -- bright black
    '{colors.get("term9", "#FB4934")}',  -- bright red
    '{colors.get("term10", "#B8BB26")}', -- bright green
    '{colors.get("term11", "#FABD2F")}', -- bright yellow
    '{colors.get("term12", "#83A598")}', -- bright blue
    '{colors.get("term13", "#D3869B")}', -- bright magenta
    '{colors.get("term14", "#8EC07C")}', -- bright cyan
    '{colors.get("term15", "#EBDBB2")}', -- bright white
  }},

  tab_bar = {{
    background = '{colors.get("term0", "#282828")}',
    active_tab = {{
      bg_color = '{colors.get("primary", "#458588")}',
      fg_color = '{colors.get("onPrimary", "#FFFFFF")}',
    }},
    inactive_tab = {{
      bg_color = '{colors.get("term8", "#928374")}',
      fg_color = '{colors.get("term7", "#A89984")}',
    }},
    inactive_tab_hover = {{
      bg_color = '{colors.get("term8", "#928374")}',
      fg_color = '{colors.get("term15", "#EBDBB2")}',
    }},
  }},
}}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into wezterm.lua
    home = os.path.expanduser("~")
    wezterm_conf = f"{home}/.config/wezterm/wezterm.lua"
    integration_code = """local wezterm = require('wezterm')
local config = wezterm.config_builder()
local colors = require('colors')
config.colors = colors
return config
"""

    wezterm_path = Path(wezterm_conf)
    if wezterm_path.exists():
        content = wezterm_path.read_text()
        if "require('colors')" not in content:
            # Add color loading to existing config
            lines = content.split("\n")
            # Find return config line and insert before it
            for i, line in enumerate(lines):
                if "return config" in line or "return {" in line:
                    lines.insert(i, "local colors = require('colors')")
                    lines.insert(i + 1, "config.colors = colors")
                    break
            wezterm_path.write_text("\n".join(lines))
            print(f"✓ Generated WezTerm config and auto-integrated")
        else:
            print(f"✓ Generated WezTerm config (already integrated)")
    else:
        wezterm_path.parent.mkdir(parents=True, exist_ok=True)
        wezterm_path.write_text(integration_code)
        print(f"✓ Generated WezTerm config and auto-integrated (created config)")


def generate_ghostty_config(colors, output_path):
    """Generate Ghostty terminal color config and auto-integrate"""
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

background = {colors.get("term0", "#282828")}
foreground = {colors.get("term7", "#A89984")}

cursor-color = {colors.get("term7", "#A89984")}
cursor-text = {colors.get("term0", "#282828")}

selection-background = {colors.get("term7", "#A89984")}
selection-foreground = {colors.get("term0", "#282828")}

# Black
palette = 0={colors.get("term0", "#282828")}
palette = 8={colors.get("term8", "#928374")}

# Red
palette = 1={colors.get("term1", "#CC241D")}
palette = 9={colors.get("term9", "#FB4934")}

# Green
palette = 2={colors.get("term2", "#98971A")}
palette = 10={colors.get("term10", "#B8BB26")}

# Yellow
palette = 3={colors.get("term3", "#D79921")}
palette = 11={colors.get("term11", "#FABD2F")}

# Blue
palette = 4={colors.get("term4", "#458588")}
palette = 12={colors.get("term12", "#83A598")}

# Magenta
palette = 5={colors.get("term5", "#B16286")}
palette = 13={colors.get("term13", "#D3869B")}

# Cyan
palette = 6={colors.get("term6", "#689D6A")}
palette = 14={colors.get("term14", "#8EC07C")}

# White
palette = 7={colors.get("term7", "#A89984")}
palette = 15={colors.get("term15", "#EBDBB2")}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into ghostty config
    home = os.path.expanduser("~")
    ghostty_conf = f"{home}/.config/ghostty/config"
    if ensure_line_in_file(ghostty_conf, "theme = ii-auto", r"theme\s*=\s*ii-auto"):
        print(f"✓ Generated Ghostty config and auto-integrated")
    else:
        print(f"✓ Generated Ghostty config (already integrated)")


def generate_konsole_config(colors, output_path):
    """Generate Konsole terminal color config"""
    config = f"""[Background]
Color={colors.get("term0", "#282828")[1:]}

[BackgroundIntense]
Color={colors.get("term0", "#282828")[1:]}

[Foreground]
Color={colors.get("term7", "#A89984")[1:]}

[ForegroundIntense]
Color={colors.get("term15", "#EBDBB2")[1:]}

[Color0]
Color={colors.get("term0", "#282828")[1:]}

[Color0Intense]
Color={colors.get("term8", "#928374")[1:]}

[Color1]
Color={colors.get("term1", "#CC241D")[1:]}

[Color1Intense]
Color={colors.get("term9", "#FB4934")[1:]}

[Color2]
Color={colors.get("term2", "#98971A")[1:]}

[Color2Intense]
Color={colors.get("term10", "#B8BB26")[1:]}

[Color3]
Color={colors.get("term3", "#D79921")[1:]}

[Color3Intense]
Color={colors.get("term11", "#FABD2F")[1:]}

[Color4]
Color={colors.get("term4", "#458588")[1:]}

[Color4Intense]
Color={colors.get("term12", "#83A598")[1:]}

[Color5]
Color={colors.get("term5", "#B16286")[1:]}

[Color5Intense]
Color={colors.get("term13", "#D3869B")[1:]}

[Color6]
Color={colors.get("term6", "#689D6A")[1:]}

[Color6Intense]
Color={colors.get("term14", "#8EC07C")[1:]}

[Color7]
Color={colors.get("term7", "#A89984")[1:]}

[Color7Intense]
Color={colors.get("term15", "#EBDBB2")[1:]}

[General]
Description=ii Auto-generated Theme
Opacity=1.0
Wallpaper=
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)
    print(f"✓ Generated Konsole config")


def generate_starship_config(colors, output_path):
    """Generate Starship prompt palette config and auto-integrate"""
    # Starship uses a TOML palette format
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten
# This file provides Material You colors to your Starship prompt

[palettes.ii]
primary = '{colors.get("primary", "#458588")}'
onPrimary = '{colors.get("onPrimary", "#FFFFFF")}'
secondary = '{colors.get("secondary", "#83A598")}'
onSecondary = '{colors.get("onSecondary", "#1D2021")}'
tertiary = '{colors.get("tertiary", "#D3869B")}'
onTertiary = '{colors.get("onTertiary", "#1D2021")}'
surface = '{colors.get("surface", "#1D2021")}'
onSurface = '{colors.get("onSurface", "#EBDBB2")}'
background = '{colors.get("term0", "#282828")}'
foreground = '{colors.get("term7", "#A89984")}'
black = '{colors.get("term0", "#282828")}'
red = '{colors.get("term1", "#CC241D")}'
green = '{colors.get("term2", "#98971A")}'
yellow = '{colors.get("term3", "#D79921")}'
blue = '{colors.get("term4", "#458588")}'
magenta = '{colors.get("term5", "#B16286")}'
cyan = '{colors.get("term6", "#689D6A")}'
white = '{colors.get("term7", "#A89984")}'
bright_black = '{colors.get("term8", "#928374")}'
bright_red = '{colors.get("term9", "#FB4934")}'
bright_green = '{colors.get("term10", "#B8BB26")}'
bright_yellow = '{colors.get("term11", "#FABD2F")}'
bright_blue = '{colors.get("term12", "#83A598")}'
bright_magenta = '{colors.get("term13", "#D3869B")}'
bright_cyan = '{colors.get("term14", "#8EC07C")}'
bright_white = '{colors.get("term15", "#EBDBB2")}'
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into starship.toml
    home = os.path.expanduser("~")
    starship_conf = f"{home}/.config/starship.toml"

    # Check if starship.toml exists
    if os.path.exists(starship_conf):
        content = Path(starship_conf).read_text()

        # Check if palette_name is already set to ii
        if 'palette = "ii"' in content:
            print(f"✓ Generated Starship palette (already using ii palette)")
        else:
            # Add palette directive if not present
            if "palette =" not in content:
                # Add at top of file
                new_content = 'palette = "ii"\n\n' + content
                Path(starship_conf).write_text(new_content)
                content = new_content
                print(f"✓ Generated Starship palette and set as active")
            else:
                print(
                    f"✓ Generated Starship palette (using different palette, change to 'palette = \"ii\"' to use)"
                )

        # Update or append the [palettes.ii] section in starship.toml
        # Starship doesn't support source/include, so palette must be inline
        if "[palettes.ii]" in content:
            # Replace existing palette section with updated colors
            # Find start of [palettes.ii] and end (next section header or EOF)
            pattern = r"\[palettes\.ii\].*?(?=\n\[|\Z)"
            # Extract just the palette block from the generated config
            palette_block = config.strip().split("\n")
            # Skip comment lines at the top, keep from [palettes.ii] onward
            palette_start = next(
                i
                for i, line in enumerate(palette_block)
                if line.startswith("[palettes.ii]")
            )
            palette_content = "\n".join(palette_block[palette_start:])
            new_content = re.sub(pattern, palette_content, content, flags=re.DOTALL)
            if new_content != content:
                Path(starship_conf).write_text(new_content)
                print(f"  → Updated ii palette in starship.toml")
        else:
            with open(starship_conf, "a") as f:
                f.write("\n" + config)
            print(f"  → Appended ii palette to starship.toml")
    else:
        print(
            f"✓ Generated Starship palette (starship.toml not found - create it and add 'palette = \"ii\"')"
        )


def generate_btop_config(colors, output_path):
    """Generate btop theme file and auto-integrate"""
    bg = colors.get("term0", "#282828")
    fg = colors.get("term15", "#EBDBB2")
    fg_dim = colors.get("term7", "#A89984")
    gray = colors.get("term8", "#928374")
    primary = colors.get("primary", "#458588")
    sel_bg = colors.get("surfaceContainer", colors.get("term8", "#3C3836"))
    red = colors.get("term1", "#CC241D")
    red_br = colors.get("term9", "#FB4934")
    green = colors.get("term2", "#98971A")
    green_br = colors.get("term10", "#B8BB26")
    yellow = colors.get("term3", "#D79921")
    yellow_br = colors.get("term11", "#FABD2F")
    blue = colors.get("term4", "#458588")
    blue_br = colors.get("term12", "#83A598")
    magenta = colors.get("term5", "#B16286")
    magenta_br = colors.get("term13", "#D3869B")
    cyan = colors.get("term6", "#689D6A")
    cyan_br = colors.get("term14", "#8EC07C")

    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

# Main bg/fg
theme[main_bg]="{bg}"
theme[main_fg]="{fg}"
theme[title]="{fg}"
theme[hi_fg]="{primary}"
theme[selected_bg]="{sel_bg}"
theme[selected_fg]="{fg}"
theme[inactive_fg]="{gray}"
theme[graph_text]="{fg_dim}"
theme[meter_bg]="{sel_bg}"
theme[proc_misc]="{yellow}"

# Box outlines
theme[cpu_box]="{blue}"
theme[mem_box]="{green}"
theme[net_box]="{magenta}"
theme[proc_box]="{cyan}"
theme[div_line]="{gray}"

# Temperature graph
theme[temp_start]="{green}"
theme[temp_mid]="{yellow}"
theme[temp_end]="{red}"

# CPU graph
theme[cpu_start]="{green}"
theme[cpu_mid]="{yellow}"
theme[cpu_end]="{red}"

# Memory
theme[free_start]="{green}"
theme[free_mid]="{green_br}"
theme[free_end]="{green}"
theme[cached_start]="{blue}"
theme[cached_mid]="{blue_br}"
theme[cached_end]="{blue}"
theme[available_start]="{magenta}"
theme[available_mid]="{magenta_br}"
theme[available_end]="{magenta}"
theme[used_start]="{green}"
theme[used_mid]="{yellow}"
theme[used_end]="{red}"

# Network
theme[download_start]="{cyan}"
theme[download_mid]="{cyan_br}"
theme[download_end]="{cyan}"
theme[upload_start]="{magenta}"
theme[upload_mid]="{magenta_br}"
theme[upload_end]="{magenta}"

# Process
theme[process_start]="{primary}"
theme[process_mid]="{blue_br}"
theme[process_end]="{primary}"
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate: set color_theme in btop.conf
    home = os.path.expanduser("~")
    btop_conf = f"{home}/.config/btop/btop.conf"
    btop_path = Path(btop_conf)
    if btop_path.exists():
        content = btop_path.read_text()
        new_line = 'color_theme = "ii-auto"'
        if re.search(r"^color_theme\s*=", content, re.MULTILINE):
            new_content = re.sub(
                r"^color_theme\s*=.*$", new_line, content, flags=re.MULTILINE
            )
            if new_content != content:
                btop_path.write_text(new_content)
                print(f"\u2713 Generated btop theme and updated btop.conf")
            else:
                print(f"\u2713 Generated btop theme (already using ii-auto)")
        else:
            with open(btop_conf, "a") as f:
                f.write(f"\n{new_line}\n")
            print(f"\u2713 Generated btop theme and added to btop.conf")
    else:
        btop_path.parent.mkdir(parents=True, exist_ok=True)
        btop_path.write_text(f'color_theme = "ii-auto"\n')
        print(f"\u2713 Generated btop theme and created btop.conf")


def generate_lazygit_config(colors, output_path):
    """Generate lazygit theme config.

    Writes a standalone theme YAML that can be merged into config.yml.
    If config.yml exists, merges the gui.theme section carefully.
    """
    primary = colors.get("primary", "#458588")
    fg = colors.get("term15", "#EBDBB2")
    gray = colors.get("term8", "#928374")
    sel_bg = colors.get("surfaceContainer", colors.get("term8", "#3C3836"))
    red = colors.get("term1", "#CC241D")
    yellow = colors.get("term3", "#D79921")
    green = colors.get("term2", "#98971A")
    blue = colors.get("term4", "#458588")
    magenta = colors.get("term5", "#B16286")

    # The theme block we want inside config.yml
    theme_yaml = f"""    theme:
      activeBorderColor:
        - "{primary}"
        - bold
      inactiveBorderColor:
        - "{gray}"
      optionsTextColor:
        - "{primary}"
      selectedLineBgColor:
        - "{sel_bg}"
      selectedRangeBgColor:
        - "{sel_bg}"
      cherryPickedCommitFgColor:
        - "{primary}"
      cherryPickedCommitBgColor:
        - "{sel_bg}"
      markedBaseCommitFgColor:
        - "{yellow}"
      markedBaseCommitBgColor:
        - "{sel_bg}"
      unstagedChangesColor:
        - "{red}"
      defaultFgColor:
        - "{fg}"
"""

    home = os.path.expanduser("~")
    config_path = f"{home}/.config/lazygit/config.yml"
    config_file = Path(config_path)

    # Also write standalone theme file for reference
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(f"# Auto-generated by ii wallpaper theming system\n")
        f.write(f"# This is the theme section for lazygit config.yml\n")
        f.write(f"gui:\n{theme_yaml}\n")

    if config_file.exists():
        content = config_file.read_text()
        # Check if gui.theme section exists
        if re.search(r"^\s*theme:", content, re.MULTILINE):
            # Replace existing theme block
            # Find "    theme:" and everything indented under it until next key at same/less indent
            pattern = r"(    theme:\n(?:      .*\n)*(?:        .*\n)*)"
            new_content = re.sub(pattern, theme_yaml + "\n", content, count=1)
            if new_content != content:
                config_file.write_text(new_content)
                print(f"\u2713 Generated lazygit theme and updated config.yml")
            else:
                print(f"\u2713 Generated lazygit theme (config.yml unchanged)")
        elif re.search(r"^gui:", content, re.MULTILINE):
            # gui: exists but no theme: — insert theme after gui:
            new_content = re.sub(
                r"^(gui:.*)", r"\1\n" + theme_yaml, content, count=1, flags=re.MULTILINE
            )
            config_file.write_text(new_content)
            print(f"\u2713 Generated lazygit theme and added to gui section")
        else:
            # No gui: section at all — append
            with open(config_path, "a") as f:
                f.write(f"\ngui:\n{theme_yaml}\n")
            print(f"\u2713 Generated lazygit theme and appended gui section")
    else:
        config_file.parent.mkdir(parents=True, exist_ok=True)
        config_file.write_text(f"gui:\n{theme_yaml}\n")
        print(f"\u2713 Generated lazygit config with theme")


def generate_yazi_config(colors, output_path):
    """Generate yazi flavor for ii theming.

    Creates a flavor directory at ~/.config/yazi/flavors/ii-auto.yazi/
    with a flavor.toml that uses the material colors.
    """
    bg = colors.get("term0", "#282828")
    fg = colors.get("term15", "#EBDBB2")
    fg_dim = colors.get("term7", "#A89984")
    gray = colors.get("term8", "#928374")
    primary = colors.get("primary", "#458588")
    sel_bg = colors.get("surfaceContainer", colors.get("term8", "#3C3836"))
    red = colors.get("term1", "#CC241D")
    green = colors.get("term2", "#98971A")
    yellow = colors.get("term3", "#D79921")
    blue = colors.get("term4", "#458588")
    magenta = colors.get("term5", "#B16286")
    cyan = colors.get("term6", "#689D6A")

    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

[mgr]
cwd = {{ fg = "{primary}" }}
hovered         = {{ fg = "{bg}", bg = "{primary}" }}
preview_hovered = {{ underline = true }}
find_keyword    = {{ fg = "{yellow}", italic = true }}
find_position   = {{ fg = "{magenta}", bg = "reset", italic = true }}
marker_selected = {{ fg = "{green}", bg = "{green}" }}
marker_copied   = {{ fg = "{yellow}", bg = "{yellow}" }}
marker_cut      = {{ fg = "{red}", bg = "{red}" }}
tab_active      = {{ fg = "{bg}", bg = "{sel_bg}" }}
tab_inactive    = {{ fg = "{fg_dim}", bg = "{sel_bg}" }}
tab_width       = 1
border_symbol   = "\u2502"
border_style    = {{ fg = "{gray}" }}
count_copied    = {{ fg = "{bg}", bg = "{yellow}" }}
count_cut       = {{ fg = "{bg}", bg = "{red}" }}
count_selected  = {{ fg = "{bg}", bg = "{primary}" }}

[mode]
normal_main = {{ fg = "{bg}", bg = "{primary}", bold = true }}
normal_alt  = {{ fg = "{bg}", bg = "{primary}", bold = true }}
select_main = {{ fg = "{bg}", bg = "{green}", bold = true }}
select_alt  = {{ fg = "{bg}", bg = "{green}", bold = true }}
unset_main  = {{ fg = "{bg}", bg = "{magenta}", bold = true }}
unset_alt   = {{ fg = "{bg}", bg = "{magenta}", bold = true }}

[status]
separator_open  = ""
separator_close = ""
separator_style = {{ fg = "{sel_bg}", bg = "{sel_bg}" }}
progress_label  = {{ fg = "{fg}", bold = true }}
progress_normal = {{ fg = "{primary}", bg = "{sel_bg}" }}
progress_error  = {{ fg = "{red}", bg = "{sel_bg}" }}
permissions_t   = {{ fg = "{primary}" }}
permissions_r   = {{ fg = "{yellow}" }}
permissions_w   = {{ fg = "{red}" }}
permissions_x   = {{ fg = "{green}" }}
permissions_s   = {{ fg = "{gray}" }}

[input]
border   = {{ fg = "{primary}" }}
title    = {{}}
value    = {{}}
selected = {{ reversed = true }}

[select]
border   = {{ fg = "{primary}" }}
active   = {{ fg = "{magenta}", bold = true }}
inactive = {{}}

[tasks]
border  = {{ fg = "{primary}" }}
title   = {{}}
hovered = {{ underline = true }}

[which]
mask            = {{ bg = "{sel_bg}" }}
cand            = {{ fg = "{cyan}" }}
rest            = {{ fg = "{gray}" }}
desc            = {{ fg = "{magenta}" }}
separator       = "  "
separator_style = {{ fg = "{gray}" }}

[help]
on      = {{ fg = "{magenta}" }}
run     = {{ fg = "{cyan}" }}
desc    = {{ fg = "{gray}" }}
hovered = {{ bg = "{sel_bg}", bold = true }}
footer  = {{ fg = "{sel_bg}", bg = "{fg_dim}" }}

[filetype]
rules = [
  {{ mime = "image/*", fg = "{magenta}" }},
  {{ mime = "video/*", fg = "{cyan}" }},
  {{ mime = "audio/*", fg = "{cyan}" }},
  {{ mime = "application/zip",             fg = "{red}" }},
  {{ mime = "application/gzip",            fg = "{red}" }},
  {{ mime = "application/x-tar",           fg = "{red}" }},
  {{ mime = "application/x-bzip",          fg = "{red}" }},
  {{ mime = "application/x-bzip2",         fg = "{red}" }},
  {{ mime = "application/x-7z-compressed", fg = "{red}" }},
  {{ mime = "application/x-rar",           fg = "{red}" }},
  {{ name = "*",  fg = "{fg_dim}" }},
  {{ name = "*/", fg = "{primary}" }},
]
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate: set flavor in yazi's theme.toml
    home = os.path.expanduser("~")
    theme_toml = f"{home}/.config/yazi/theme.toml"
    theme_path = Path(theme_toml)

    flavor_line = 'use = "ii-auto"'
    if theme_path.exists():
        content = theme_path.read_text()
        if "[flavor]" in content:
            if re.search(r'^use\s*=\s*"ii-auto"', content, re.MULTILINE):
                print(f"\u2713 Generated yazi flavor (already using ii-auto)")
            elif re.search(r"^use\s*=", content, re.MULTILINE):
                new_content = re.sub(
                    r"^(use\s*=).*$",
                    f'use = "ii-auto"',
                    content,
                    count=1,
                    flags=re.MULTILINE,
                )
                theme_path.write_text(new_content)
                print(f"\u2713 Generated yazi flavor and updated theme.toml")
            else:
                new_content = content.replace("[flavor]", f"[flavor]\n{flavor_line}")
                theme_path.write_text(new_content)
                print(f"\u2713 Generated yazi flavor and added use directive")
        else:
            with open(theme_toml, "a") as f:
                f.write(f"\n[flavor]\n{flavor_line}\n")
            print(f"\u2713 Generated yazi flavor and added [flavor] section")
    else:
        theme_path.parent.mkdir(parents=True, exist_ok=True)
        theme_path.write_text(f"[flavor]\n{flavor_line}\n")
        print(f"\u2713 Generated yazi flavor and created theme.toml")


def generate_fuzzel_config(colors, output_path):
    """Generate Fuzzel launcher theme from material colors"""
    bg = colors.get("background", colors.get("term0", "#282828"))
    fg = colors.get("onBackground", colors.get("term15", "#EBDBB2"))
    surface_var = colors.get("surfaceVariant", colors.get("term8", "#928374"))
    on_surface_var = colors.get("onSurfaceVariant", colors.get("term7", "#A89984"))
    primary = colors.get("primary", "#458588")

    # Strip '#' and add 'ff' alpha
    def hex_alpha(c):
        return c[1:] + "ff" if c.startswith("#") else c + "ff"

    def hex_alpha_dim(c):
        return c[1:] + "dd" if c.startswith("#") else c + "dd"

    config = f"""[colors]
background={hex_alpha(bg)}
text={hex_alpha(fg)}
selection={hex_alpha(surface_var)}
selection-text={hex_alpha(on_surface_var)}
border={hex_alpha_dim(surface_var)}
match={hex_alpha(primary)}
selection-match={hex_alpha(primary)}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)
    print(f"\u2713 Generated Fuzzel theme")


def generate_pywalfox_config(colors, output_path):
    """Generate Pywalfox-compatible JSON from material colors"""
    import json

    bg = colors.get("background", colors.get("term0", "#282828"))
    fg = colors.get("onBackground", colors.get("term15", "#EBDBB2"))
    primary = colors.get("primary", "#458588")

    # Build 16-color palette from term colors
    palette = {}
    for i in range(16):
        palette[f"color{i}"] = colors.get(f"term{i}", "#000000")

    # Read wallpaper path if available
    wallpaper = ""
    wp_path = os.path.expanduser(
        "~/.local/state/quickshell/user/generated/wallpaper/path.txt"
    )
    if os.path.exists(wp_path):
        with open(wp_path) as f:
            wallpaper = f.read().strip()

    pywalfox_data = {
        "wallpaper": wallpaper,
        "alpha": "100",
        "colors": palette,
        "special": {
            "background": bg,
            "foreground": fg,
            "cursor": primary,
        },
    }

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(pywalfox_data, f, indent=2)
    print(f"\u2713 Generated Pywalfox colors")


def generate_zed_config(colors, scss_path, output_path):
    """Generate Zed editor theme from Material You colors and SCSS terminal colors."""
    # Load colors.json for Material You colors
    colors_json_path = os.path.expanduser(
        "~/.local/state/quickshell/user/generated/colors.json"
    )

    try:
        with open(colors_json_path, "r") as f:
            my_colors = json.load(f)
    except FileNotFoundError:
        print(
            f"Warning: Could not find colors.json. Using defaults for Zed theme.",
            file=sys.stderr,
        )
        my_colors = {
            "primary": "#7aa2f7",
            "secondary": "#bb9af7",
            "tertiary": "#9ece6a",
            "error": "#f7768e",
            "surface": "#1a1b26",
            "surface_container_low": "#24283b",
            "surface_container": "#414868",
            "surface_container_high": "#565f89",
            "outline": "#565f89",
            "on_surface": "#c0caf5",
            "on_surface_variant": "#9aa5ce",
            "on_primary": "#1a1b26",
        }

    my_colors = {k: v.lower() for k, v in my_colors.items()}

    # Get terminal colors from SCSS
    term_colors = parse_scss_colors(scss_path)

    def hex_with_alpha(hex_color, alpha_hex):
        """Add alpha hex value to color"""
        hex_color = hex_color.lstrip("#")
        return f"#{hex_color}{alpha_hex}"

    def adjust_lightness(hex_color, factor):
        """Adjust lightness of hex color (factor > 1 = lighter, factor < 1 = darker)"""
        hex_color = hex_color.lstrip("#")
        r = int(hex_color[0:2], 16) / 255.0
        g = int(hex_color[2:4], 16) / 255.0
        b = int(hex_color[4:6], 16) / 255.0

        max_c = max(r, g, b)
        min_c = min(r, g, b)
        l = (max_c + min_c) / 2.0

        if max_c == min_c:
            h = s = 0
        else:
            d = max_c - min_c
            s = d / (2.0 - max_c - min_c) if l > 0.5 else d / (max_c + min_c)
            if max_c == r:
                h = (g - b) / d + (6 if g < b else 0)
            elif max_c == g:
                h = (b - r) / d + 2
            else:
                h = (r - g) / d + 4
            h /= 6.0

        l = max(0.0, min(1.0, l * factor))

        def hue_to_rgb(p, q, t):
            if t < 0:
                t += 1
            if t > 1:
                t -= 1
            if t < 1 / 6:
                return p + (q - p) * 6 * t
            if t < 1 / 2:
                return q
            if t < 2 / 3:
                return p + (q - p) * (2 / 3 - t) * 6
            return p

        if s == 0:
            r = g = b = l
        else:
            q = l * (1 + s) if l < 0.5 else l + s - l * s
            p = 2 * l - q
            r = hue_to_rgb(p, q, h + 1 / 3)
            g = hue_to_rgb(p, q, h)
            b = hue_to_rgb(p, q, h - 1 / 3)

        return f"#{int(r * 255):02x}{int(g * 255):02x}{int(b * 255):02x}"

    def build_zed_dark_theme():
        primary = my_colors.get("primary", "#7aa2f7")
        secondary = my_colors.get("secondary", "#bb9af7")
        tertiary = my_colors.get("tertiary", "#9ece6a")
        error = my_colors.get("error", "#f7768e")
        surface = my_colors.get("surface", "#1a1b26")
        surface_low = my_colors.get("surface_container_low", "#24283b")
        surface_std = my_colors.get("surface_container", "#414868")
        surface_high = my_colors.get("surface_container_high", "#565f89")
        outline = my_colors.get("outline", "#565f89")
        on_surface = my_colors.get("on_surface", "#c0caf5")
        on_surface_variant = my_colors.get("on_surface_variant", "#9aa5ce")

        theme = {
            "border": hex_with_alpha(outline, "ff"),
            "border.variant": hex_with_alpha(adjust_lightness(surface_low, 0.8), "ff"),
            "border.focused": hex_with_alpha(primary, "ff"),
            "border.selected": hex_with_alpha(adjust_lightness(primary, 0.7), "ff"),
            "border.transparent": "#00000000",
            "border.disabled": hex_with_alpha(adjust_lightness(outline, 0.5), "ff"),
            "elevated_surface.background": hex_with_alpha(surface_low, "ff"),
            "surface.background": hex_with_alpha(surface_low, "ff"),
            "background": hex_with_alpha(surface, "ff"),
            "element.background": hex_with_alpha(surface_low, "ff"),
            "element.hover": hex_with_alpha(surface_std, "ff"),
            "element.active": hex_with_alpha(surface_high, "ff"),
            "element.selected": hex_with_alpha(surface_high, "ff"),
            "element.disabled": hex_with_alpha(surface_low, "ff"),
            "drop_target.background": hex_with_alpha(primary, "80"),
            "ghost_element.background": "#00000000",
            "ghost_element.hover": hex_with_alpha(surface_std, "ff"),
            "ghost_element.active": hex_with_alpha(surface_high, "ff"),
            "ghost_element.selected": hex_with_alpha(surface_high, "ff"),
            "ghost_element.disabled": hex_with_alpha(surface_low, "ff"),
            "text": hex_with_alpha(on_surface, "ff"),
            "text.muted": hex_with_alpha(on_surface_variant, "ff"),
            "text.placeholder": hex_with_alpha(
                adjust_lightness(on_surface_variant, 0.7), "ff"
            ),
            "text.disabled": hex_with_alpha(
                adjust_lightness(on_surface_variant, 0.6), "ff"
            ),
            "text.accent": hex_with_alpha(primary, "ff"),
            "icon": hex_with_alpha(on_surface, "ff"),
            "icon.muted": hex_with_alpha(on_surface_variant, "ff"),
            "icon.disabled": hex_with_alpha(
                adjust_lightness(on_surface_variant, 0.6), "ff"
            ),
            "icon.placeholder": hex_with_alpha(on_surface_variant, "ff"),
            "icon.accent": hex_with_alpha(primary, "ff"),
            "status_bar.background": hex_with_alpha(surface, "ff"),
            "title_bar.background": hex_with_alpha(surface, "ff"),
            "title_bar.inactive_background": hex_with_alpha(surface_low, "ff"),
            "toolbar.background": hex_with_alpha(surface_low, "ff"),
            "tab_bar.background": hex_with_alpha(surface_low, "ff"),
            "tab.inactive_background": hex_with_alpha(surface_low, "ff"),
            "tab.active_background": hex_with_alpha(
                adjust_lightness(surface, 0.9), "ff"
            ),
            "search.match_background": hex_with_alpha(primary, "66"),
            "search.active_match_background": hex_with_alpha(tertiary, "66"),
            "panel.background": hex_with_alpha(surface_low, "ff"),
            "panel.focused_border": None,
            "pane.focused_border": None,
            "scrollbar.thumb.background": hex_with_alpha(on_surface_variant, "4c"),
            "scrollbar.thumb.hover_background": hex_with_alpha(surface_high, "ff"),
            "scrollbar.thumb.border": hex_with_alpha(surface_std, "ff"),
            "scrollbar.track.background": "#00000000",
            "scrollbar.track.border": hex_with_alpha(surface_std, "ff"),
            "editor.foreground": hex_with_alpha(on_surface, "ff"),
            "editor.background": hex_with_alpha(surface, "ff"),
            "editor.gutter.background": hex_with_alpha(surface, "ff"),
            "editor.subheader.background": hex_with_alpha(surface_low, "ff"),
            "editor.active_line.background": hex_with_alpha(surface_low, "bf"),
            "editor.highlighted_line.background": hex_with_alpha(surface_std, "ff"),
            "editor.line_number": hex_with_alpha(on_surface_variant, "ff"),
            "editor.active_line_number": hex_with_alpha(on_surface, "ff"),
            "editor.hover_line_number": hex_with_alpha(
                adjust_lightness(on_surface, 1.1), "ff"
            ),
            "editor.invisible": hex_with_alpha(on_surface_variant, "ff"),
            "editor.wrap_guide": hex_with_alpha(on_surface_variant, "0d"),
            "editor.active_wrap_guide": hex_with_alpha(on_surface_variant, "1a"),
            "editor.document_highlight.read_background": hex_with_alpha(primary, "1a"),
            "editor.document_highlight.write_background": hex_with_alpha(
                surface_std, "66"
            ),
            "terminal.background": hex_with_alpha(surface, "ff"),
            "terminal.foreground": hex_with_alpha(on_surface, "ff"),
            "terminal.bright_foreground": hex_with_alpha(on_surface, "ff"),
            "terminal.dim_foreground": hex_with_alpha(
                adjust_lightness(on_surface, 0.6), "ff"
            ),
            "link_text.hover": hex_with_alpha(primary, "ff"),
            "version_control.added": hex_with_alpha(tertiary, "ff"),
            "version_control.modified": hex_with_alpha(
                adjust_lightness(primary, 0.8), "ff"
            ),
            "version_control.word_added": hex_with_alpha(tertiary, "59"),
            "version_control.word_deleted": hex_with_alpha(error, "cc"),
            "version_control.deleted": hex_with_alpha(error, "ff"),
            "version_control.conflict_marker.ours": hex_with_alpha(tertiary, "1a"),
            "version_control.conflict_marker.theirs": hex_with_alpha(primary, "1a"),
            "conflict": hex_with_alpha(adjust_lightness(tertiary, 0.8), "ff"),
            "conflict.background": hex_with_alpha(
                adjust_lightness(tertiary, 0.8), "1a"
            ),
            "conflict.border": hex_with_alpha(adjust_lightness(tertiary, 0.6), "ff"),
            "created": hex_with_alpha(tertiary, "ff"),
            "created.background": hex_with_alpha(tertiary, "1a"),
            "created.border": hex_with_alpha(adjust_lightness(tertiary, 0.6), "ff"),
            "deleted": hex_with_alpha(error, "ff"),
            "deleted.background": hex_with_alpha(error, "1a"),
            "deleted.border": hex_with_alpha(adjust_lightness(error, 0.6), "ff"),
            "error": hex_with_alpha(error, "ff"),
            "error.background": hex_with_alpha(error, "1a"),
            "error.border": hex_with_alpha(adjust_lightness(error, 0.6), "ff"),
            "hidden": hex_with_alpha(on_surface_variant, "ff"),
            "hidden.background": hex_with_alpha(
                adjust_lightness(on_surface_variant, 0.3), "1a"
            ),
            "hidden.border": hex_with_alpha(outline, "ff"),
            "hint": hex_with_alpha(adjust_lightness(primary, 0.7), "ff"),
            "hint.background": hex_with_alpha(adjust_lightness(primary, 0.7), "1a"),
            "hint.border": hex_with_alpha(adjust_lightness(primary, 0.6), "ff"),
            "ignored": hex_with_alpha(on_surface_variant, "ff"),
            "ignored.background": hex_with_alpha(
                adjust_lightness(on_surface_variant, 0.3), "1a"
            ),
            "ignored.border": hex_with_alpha(outline, "ff"),
            "info": hex_with_alpha(primary, "ff"),
            "info.background": hex_with_alpha(primary, "1a"),
            "info.border": hex_with_alpha(adjust_lightness(primary, 0.6), "ff"),
            "modified": hex_with_alpha(adjust_lightness(primary, 0.8), "ff"),
            "modified.background": hex_with_alpha(adjust_lightness(primary, 0.8), "1a"),
            "modified.border": hex_with_alpha(
                adjust_lightness(adjust_lightness(primary, 0.8), 0.6), "ff"
            ),
            "predictive": hex_with_alpha(adjust_lightness(secondary, 0.8), "ff"),
            "predictive.background": hex_with_alpha(
                adjust_lightness(secondary, 0.8), "1a"
            ),
            "predictive.border": hex_with_alpha(
                adjust_lightness(adjust_lightness(secondary, 0.8), 0.6), "ff"
            ),
            "renamed": hex_with_alpha(primary, "ff"),
            "renamed.background": hex_with_alpha(primary, "1a"),
            "renamed.border": hex_with_alpha(adjust_lightness(primary, 0.6), "ff"),
            "success": hex_with_alpha(tertiary, "ff"),
            "success.background": hex_with_alpha(tertiary, "1a"),
            "success.border": hex_with_alpha(adjust_lightness(tertiary, 0.6), "ff"),
            "unreachable": hex_with_alpha(on_surface_variant, "ff"),
            "unreachable.background": hex_with_alpha(
                adjust_lightness(on_surface_variant, 0.3), "1a"
            ),
            "unreachable.border": hex_with_alpha(outline, "ff"),
            "warning": hex_with_alpha(adjust_lightness(tertiary, 0.9), "ff"),
            "warning.background": hex_with_alpha(adjust_lightness(tertiary, 0.9), "1a"),
            "warning.border": hex_with_alpha(
                adjust_lightness(adjust_lightness(tertiary, 0.9), 0.6), "ff"
            ),
        }

        # Terminal colors
        for i in range(16):
            term_color = term_colors.get(
                f"term{i}", f"#{282828 if i == 0 else 'ffffff'}"
            )
            theme[f"terminal.ansi.black"] = (
                hex_with_alpha(term_colors.get("term0", "#000000"), "ff")
                if i == 0
                else theme.get("terminal.ansi.black")
            )
            theme[f"terminal.ansi.bright_black"] = (
                hex_with_alpha(term_colors.get("term8", "#555555"), "ff")
                if i == 8
                else theme.get("terminal.ansi.bright_black")
            )
            theme[f"terminal.ansi.dim_black"] = (
                hex_with_alpha(
                    adjust_lightness(term_colors.get("term0", "#000000"), 0.6), "ff"
                )
                if i == 0
                else theme.get("terminal.ansi.dim_black")
            )

        color_map = {
            "red": 1,
            "bright_red": 9,
            "dim_red": 1,
            "green": 2,
            "bright_green": 10,
            "dim_green": 2,
            "yellow": 3,
            "bright_yellow": 11,
            "dim_yellow": 3,
            "blue": 4,
            "bright_blue": 12,
            "dim_blue": 4,
            "magenta": 5,
            "bright_magenta": 13,
            "dim_magenta": 5,
            "cyan": 6,
            "bright_cyan": 14,
            "dim_cyan": 6,
            "white": 7,
            "bright_white": 15,
            "dim_white": 7,
        }

        for name, idx in color_map.items():
            base_color = term_colors.get(f"term{idx}", "#ffffff")
            if "bright" in name:
                color = adjust_lightness(base_color, 1.2)
            elif "dim" in name:
                color = adjust_lightness(base_color, 0.7)
            else:
                color = base_color
            theme[f"terminal.ansi.{name}"] = hex_with_alpha(color, "ff")

        # Players
        player_colors = [
            primary,
            error,
            adjust_lightness(tertiary, 0.8),
            secondary,
            adjust_lightness(secondary, 1.2),
            adjust_lightness(error, 0.8),
            adjust_lightness(tertiary, 0.9),
            adjust_lightness(primary, 0.8),
        ]
        theme["players"] = [
            {
                "cursor": hex_with_alpha(color, "ff"),
                "background": hex_with_alpha(color, "ff"),
                "selection": hex_with_alpha(color, "3d"),
            }
            for color in player_colors
        ]

        # Syntax highlighting
        theme["syntax"] = {
            "attribute": {
                "color": hex_with_alpha(primary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "boolean": {
                "color": hex_with_alpha(adjust_lightness(tertiary, 0.8), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "comment": {
                "color": hex_with_alpha(
                    adjust_lightness(on_surface_variant, 0.7), "ff"
                ),
                "font_style": None,
                "font_weight": None,
            },
            "comment.doc": {
                "color": hex_with_alpha(
                    adjust_lightness(on_surface_variant, 0.8), "ff"
                ),
                "font_style": None,
                "font_weight": None,
            },
            "constant": {
                "color": hex_with_alpha(adjust_lightness(tertiary, 0.9), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "constructor": {
                "color": hex_with_alpha(primary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "embedded": {
                "color": hex_with_alpha(on_surface, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "emphasis": {
                "color": hex_with_alpha(primary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "emphasis.strong": {
                "color": hex_with_alpha(adjust_lightness(tertiary, 0.8), "ff"),
                "font_style": None,
                "font_weight": 700,
            },
            "enum": {
                "color": hex_with_alpha(secondary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "function": {
                "color": hex_with_alpha(primary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "hint": {
                "color": hex_with_alpha(adjust_lightness(primary, 0.7), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "keyword": {
                "color": hex_with_alpha(secondary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "label": {
                "color": hex_with_alpha(primary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "link_text": {
                "color": hex_with_alpha(primary, "ff"),
                "font_style": "normal",
                "font_weight": None,
            },
            "link_uri": {
                "color": hex_with_alpha(secondary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "namespace": {
                "color": hex_with_alpha(on_surface, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "number": {
                "color": hex_with_alpha(adjust_lightness(tertiary, 0.8), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "operator": {
                "color": hex_with_alpha(secondary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "predictive": {
                "color": hex_with_alpha(adjust_lightness(secondary, 0.8), "ff"),
                "font_style": "italic",
                "font_weight": None,
            },
            "preproc": {
                "color": hex_with_alpha(on_surface, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "primary": {
                "color": hex_with_alpha(on_surface, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "property": {
                "color": hex_with_alpha(adjust_lightness(primary, 0.85), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "punctuation": {
                "color": hex_with_alpha(on_surface, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "punctuation.bracket": {
                "color": hex_with_alpha(adjust_lightness(on_surface, 0.9), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "punctuation.delimiter": {
                "color": hex_with_alpha(adjust_lightness(on_surface, 0.9), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "punctuation.list_marker": {
                "color": hex_with_alpha(adjust_lightness(primary, 0.85), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "punctuation.markup": {
                "color": hex_with_alpha(adjust_lightness(primary, 0.85), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "punctuation.special": {
                "color": hex_with_alpha(adjust_lightness(error, 0.8), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "selector": {
                "color": hex_with_alpha(adjust_lightness(tertiary, 0.9), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "selector.pseudo": {
                "color": hex_with_alpha(primary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "string": {
                "color": hex_with_alpha(tertiary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "string.escape": {
                "color": hex_with_alpha(
                    adjust_lightness(on_surface_variant, 0.8), "ff"
                ),
                "font_style": None,
                "font_weight": None,
            },
            "string.regex": {
                "color": hex_with_alpha(adjust_lightness(tertiary, 0.8), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "string.special": {
                "color": hex_with_alpha(adjust_lightness(tertiary, 0.8), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "string.special.symbol": {
                "color": hex_with_alpha(adjust_lightness(tertiary, 0.8), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "tag": {
                "color": hex_with_alpha(primary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "text.literal": {
                "color": hex_with_alpha(tertiary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "title": {
                "color": hex_with_alpha(adjust_lightness(primary, 0.85), "ff"),
                "font_style": None,
                "font_weight": 400,
            },
            "type": {
                "color": hex_with_alpha(secondary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "variable": {
                "color": hex_with_alpha(on_surface, "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "variable.special": {
                "color": hex_with_alpha(adjust_lightness(tertiary, 0.8), "ff"),
                "font_style": None,
                "font_weight": None,
            },
            "variant": {
                "color": hex_with_alpha(primary, "ff"),
                "font_style": None,
                "font_weight": None,
            },
        }

        return theme

    def build_zed_light_theme():
        dark_theme = build_zed_dark_theme()

        light_theme = {}
        for key, value in dark_theme.items():
            if isinstance(value, dict):
                light_theme[key] = value.copy()
            elif value is None:
                light_theme[key] = None
            else:
                if "background" in key.lower():
                    light_theme[key] = adjust_lightness(value, 3.5)
                elif "foreground" in key.lower() or key in [
                    "text",
                    "icon",
                    "editor.foreground",
                    "terminal.foreground",
                ]:
                    light_theme[key] = adjust_lightness(value, 0.3)
                else:
                    light_theme[key] = value

        light_theme["background"] = adjust_lightness(
            my_colors.get("surface", "#ffffff"), 2.5
        )
        light_theme["surface.background"] = adjust_lightness(
            my_colors.get("surface", "#ffffff"), 2.3
        )
        light_theme["elevated_surface.background"] = adjust_lightness(
            my_colors.get("surface_container_low", "#f0f0f0"), 2.0
        )
        light_theme["element.background"] = adjust_lightness(
            my_colors.get("surface_container_low", "#f0f0f0"), 2.0
        )
        light_theme["editor.background"] = adjust_lightness(
            my_colors.get("surface", "#ffffff"), 2.5
        )
        light_theme["editor.gutter.background"] = adjust_lightness(
            my_colors.get("surface", "#ffffff"), 2.5
        )
        light_theme["terminal.background"] = adjust_lightness(
            my_colors.get("surface", "#ffffff"), 2.5
        )
        light_theme["text"] = adjust_lightness(light_theme["text"], 0.3)
        light_theme["editor.foreground"] = adjust_lightness(
            light_theme["editor.foreground"], 0.3
        )
        light_theme["terminal.foreground"] = adjust_lightness(
            light_theme["terminal.foreground"], 0.3
        )

        return light_theme

    dark_style = build_zed_dark_theme()
    light_style = build_zed_light_theme()

    theme_data = {
        "$schema": "https://zed.dev/schema/themes/v0.2.0.json",
        "name": "iNiR Material",
        "author": "iNiR Theme System",
        "themes": [
            {"name": "iNiR Dark", "appearance": "dark", "style": dark_style},
            {"name": "iNiR Light", "appearance": "light", "style": light_style},
        ],
    }

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(theme_data, f, indent=2, ensure_ascii=False)

    print(f"\u2713 Generated Zed theme")


def main():
    parser = argparse.ArgumentParser(
        description="Generate terminal color configs from material_colors.scss"
    )
    parser.add_argument(
        "--scss",
        type=str,
        default=os.path.expanduser(
            "~/.local/state/quickshell/user/generated/material_colors.scss"
        ),
        help="Path to material_colors.scss file",
    )
    parser.add_argument(
        "--terminals",
        type=str,
        nargs="+",
        choices=[
            "kitty",
            "alacritty",
            "foot",
            "wezterm",
            "ghostty",
            "konsole",
            "starship",
            "btop",
            "lazygit",
            "yazi",
            "zed",
            "all",
        ],
        default=["all"],
        help="Which terminals/tools to generate configs for",
    )

    args = parser.parse_args()

    # Parse colors from SCSS
    colors = parse_scss_colors(args.scss)

    if not colors:
        print("Error: No colors found in SCSS file", file=sys.stderr)
        sys.exit(1)

    home = os.path.expanduser("~")
    terminals = (
        args.terminals
        if "all" not in args.terminals
        else [
            "kitty",
            "alacritty",
            "foot",
            "wezterm",
            "ghostty",
            "konsole",
            "starship",
            "btop",
            "lazygit",
            "yazi",
            "zed",
        ]
    )

    # Generate configs for requested terminals
    if "kitty" in terminals:
        generate_kitty_config(colors, f"{home}/.config/kitty/current-theme.conf")

    if "alacritty" in terminals:
        generate_alacritty_config(colors, f"{home}/.config/alacritty/colors.toml")

    if "foot" in terminals:
        generate_foot_config(colors, f"{home}/.config/foot/colors.ini")

    if "wezterm" in terminals:
        generate_wezterm_config(colors, f"{home}/.config/wezterm/colors.lua")

    if "ghostty" in terminals:
        generate_ghostty_config(colors, f"{home}/.config/ghostty/themes/ii-auto")

    if "konsole" in terminals:
        generate_konsole_config(
            colors, f"{home}/.local/share/konsole/ii-auto.colorscheme"
        )

    if "starship" in terminals:
        generate_starship_config(colors, f"{home}/.config/starship/ii-palette.toml")

    if "btop" in terminals:
        generate_btop_config(colors, f"{home}/.config/btop/themes/ii-auto.theme")

    if "lazygit" in terminals:
        generate_lazygit_config(colors, f"{home}/.config/lazygit/ii-theme.yml")

    if "yazi" in terminals:
        generate_yazi_config(
            colors, f"{home}/.config/yazi/flavors/ii-auto.yazi/flavor.toml"
        )

    if "zed" in terminals:
        generate_zed_config(
            colors, args.scss, f"{home}/.config/zed/themes/ii-theme.json"
        )


if __name__ == "__main__":
    main()
