#!/usr/bin/env python3
"""
Generate terminal color configuration files from material_colors.scss
Supports: Kitty, Alacritty, Foot, WezTerm, Ghostty, Konsole
Auto-integrates into existing terminal configs
"""

import sys
import os
import re
import argparse
from pathlib import Path
from datetime import datetime


def parse_scss_colors(scss_path):
    """Parse material_colors.scss and extract color variables"""
    colors = {}
    try:
        with open(scss_path, "r") as f:
            for line in f:
                # Match lines like: $term0: #282828;
                match = re.match(r"\$(\w+):\s*(#[A-Fa-f0-9]{6});", line.strip())
                if match:
                    name, value = match.groups()
                    colors[name] = value
    except FileNotFoundError:
        print(f"Error: Could not find {scss_path}", file=sys.stderr)
        sys.exit(1)
    return colors


def ensure_line_in_file(filepath, line_to_add, check_pattern=None, at_top=False):
    """Add a line to a file if it doesn't exist. Creates file if needed."""
    filepath = Path(filepath)
    filepath.parent.mkdir(parents=True, exist_ok=True)

    # Check if file exists and if line already present
    if filepath.exists():
        content = filepath.read_text()
        if check_pattern:
            if re.search(check_pattern, content):
                return False  # Already present
        elif line_to_add in content:
            return False  # Already present
    else:
        content = ""

    # Add line
    if at_top:
        # Add at the beginning of file
        content = line_to_add + "\n" + content
    else:
        # Add at the end
        if content and not content.endswith("\n"):
            content += "\n"
        content += line_to_add + "\n"

    filepath.write_text(content)
    return True  # Added


def generate_kitty_config(colors, output_path):
    """Generate Kitty terminal color config and auto-integrate"""
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

# The basic colors
foreground              {colors.get("term7", "#A89984")}
background              {colors.get("term0", "#282828")}
selection_foreground    {colors.get("term0", "#282828")}
selection_background    {colors.get("term7", "#A89984")}

# Cursor colors
cursor                  {colors.get("term7", "#A89984")}
cursor_text_color       {colors.get("term0", "#282828")}

# URL underline color when hovering with mouse
url_color               {colors.get("term4", "#458588")}

# Kitty window border colors
active_border_color     {colors.get("primary", "#458588")}
inactive_border_color   {colors.get("term8", "#928374")}
bell_border_color       {colors.get("term1", "#CC241D")}

# Tab bar colors
active_tab_foreground   {colors.get("onPrimary", "#FFFFFF")}
active_tab_background   {colors.get("primary", "#458588")}
inactive_tab_foreground {colors.get("term7", "#A89984")}
inactive_tab_background {colors.get("term8", "#928374")}
tab_bar_background      {colors.get("term0", "#282828")}

# The 16 terminal colors

# black
color0 {colors.get("term0", "#282828")}
color8 {colors.get("term8", "#928374")}

# red
color1 {colors.get("term1", "#CC241D")}
color9 {colors.get("term9", "#FB4934")}

# green
color2  {colors.get("term2", "#98971A")}
color10 {colors.get("term10", "#B8BB26")}

# yellow
color3  {colors.get("term3", "#D79921")}
color11 {colors.get("term11", "#FABD2F")}

# blue
color4  {colors.get("term4", "#458588")}
color12 {colors.get("term12", "#83A598")}

# magenta
color5  {colors.get("term5", "#B16286")}
color13 {colors.get("term13", "#D3869B")}

# cyan
color6  {colors.get("term6", "#689D6A")}
color14 {colors.get("term14", "#8EC07C")}

# white
color7  {colors.get("term7", "#A89984")}
color15 {colors.get("term15", "#EBDBB2")}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into kitty.conf
    home = os.path.expanduser("~")
    kitty_conf = f"{home}/.config/kitty/kitty.conf"
    if ensure_line_in_file(
        kitty_conf, "include current-theme.conf", r"include\s+current-theme\.conf"
    ):
        print(f"✓ Generated Kitty config and auto-integrated")
    else:
        print(f"✓ Generated Kitty config (already integrated)")

    # Live reload kitty colors via remote control socket
    import subprocess
    import glob

    # Find kitty socket dynamically (handles PID-suffixed sockets like kitty-socket-12345)
    socket_paths = (
        ["/tmp/kitty-socket", "/tmp/kitty"]
        + glob.glob("/tmp/kitty-socket-*")
        + glob.glob("/tmp/kitty-*")
    )

    for socket_path in socket_paths:
        if os.path.exists(socket_path):
            try:
                # Use load-config instead of set-colors to reload full theme including tabs
                subprocess.run(
                    ["kitten", "@", "--to", f"unix:{socket_path}", "load-config"],
                    capture_output=True,
                    timeout=2,
                )
                print(f"  → Live-reloaded Kitty config via {socket_path}")
                break
            except Exception:
                continue


def fix_alacritty_import_order(config_path):
    """
    Fix alacritty.toml to use [general] import (Alacritty 0.15+) at the top
    and comment out hardcoded colors. Creates backup before modifying.
    Returns: (modified: bool, message: str)
    """
    try:
        with open(config_path, "r") as f:
            content = f.read()
    except FileNotFoundError:
        return False, "Config file not found"
    except PermissionError:
        return False, "Permission denied"

    import_line = 'import = ["~/.config/alacritty/colors.toml"]'
    general_import_pat = r"import\s*=\s*\[.*?colors\.toml.*?\]"
    bare_import_pat = r"^import\s*=\s*\[.*?colors\.toml.*?\]"

    has_hardcoded_colors = bool(
        re.search(r"^\[colors\.(primary|normal|bright)\]", content, re.MULTILINE)
    )

    # Check if [general] with import is already at the top (correct state)
    lines = content.split("\n")
    top_lines = [
        l.strip() for l in lines[:10] if l.strip() and not l.strip().startswith("#")
    ]

    # Correct state: [general] is first real line, import is second, no hardcoded colors
    correct = (
        len(top_lines) >= 2
        and top_lines[0] == "[general]"
        and bool(re.match(general_import_pat, top_lines[1]))
        and not has_hardcoded_colors
    )
    if correct:
        return False, "Config is already correct"

    # Create backup
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = f"{config_path}.backup_{timestamp}"
    try:
        Path(backup_path).write_text(content)
    except Exception as e:
        return False, f"Failed to create backup: {e}"

    # Build new content: [general] with import at top, then rest of config
    new_lines = [
        "# iNiR wallpaper theming - import must be at top to override colors",
        "[general]",
        import_line,
    ]

    in_general = False
    in_colors_section = False
    added_colors_comment = False

    for line in lines:
        stripped = line.strip()

        # Skip old bare import lines and their iNiR comments
        if re.match(bare_import_pat, stripped):
            continue
        if stripped.startswith("# iNiR wallpaper theming"):
            continue

        # Handle existing [general] section - absorb its non-import content
        if stripped == "[general]":
            in_general = True
            continue
        if in_general:
            if stripped.startswith("[") and stripped != "[general]":
                in_general = False
                # Fall through to process this line normally
            elif re.match(general_import_pat, stripped):
                continue  # Skip - we already added import at top
            elif stripped:
                # Move other [general] settings (live_config_reload, etc.) to top
                new_lines.append(stripped)
                continue
            else:
                continue  # Skip empty lines in old [general]

        # Comment out hardcoded color sections
        if re.match(r"^\[colors\.(primary|normal|bright|cursor|selection)\]", stripped):
            if not added_colors_comment:
                in_colors_section = True
                added_colors_comment = True
                new_lines.append("")
                new_lines.append(
                    "# Color definitions commented out by iNiR wallpaper theming"
                )
                new_lines.append(
                    "# Colors are managed via the import in [general] above"
                )
                new_lines.append("#")
            new_lines.append("# " + line)
            continue

        if in_colors_section:
            if stripped.startswith("[") and not stripped.startswith("[colors"):
                in_colors_section = False
                new_lines.append("")
                new_lines.append(line)
            elif stripped and "=" in stripped:
                new_lines.append("# " + line)
            else:
                new_lines.append("# " + line if stripped else "")
            continue

        new_lines.append(line)

    try:
        Path(config_path).write_text("\n".join(new_lines))
    except Exception as e:
        Path(config_path).write_text(content)
        return False, f"Failed to write config: {e}"

    return True, f"Fixed config (backup: {backup_path})"


def generate_alacritty_config(colors, output_path):
    """Generate Alacritty terminal color config and auto-integrate"""
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

[colors.primary]
background = '{colors.get("term0", "#282828")}'
foreground = '{colors.get("term7", "#A89984")}'

[colors.cursor]
text   = '{colors.get("term0", "#282828")}'
cursor = '{colors.get("term7", "#A89984")}'

[colors.selection]
text       = '{colors.get("term0", "#282828")}'
background = '{colors.get("term7", "#A89984")}'

[colors.normal]
black   = '{colors.get("term0", "#282828")}'
red     = '{colors.get("term1", "#CC241D")}'
green   = '{colors.get("term2", "#98971A")}'
yellow  = '{colors.get("term3", "#D79921")}'
blue    = '{colors.get("term4", "#458588")}'
magenta = '{colors.get("term5", "#B16286")}'
cyan    = '{colors.get("term6", "#689D6A")}'
white   = '{colors.get("term7", "#A89984")}'

[colors.bright]
black   = '{colors.get("term8", "#928374")}'
red     = '{colors.get("term9", "#FB4934")}'
green   = '{colors.get("term10", "#B8BB26")}'
yellow  = '{colors.get("term11", "#FABD2F")}'
blue    = '{colors.get("term12", "#83A598")}'
magenta = '{colors.get("term13", "#D3869B")}'
cyan    = '{colors.get("term14", "#8EC07C")}'
white   = '{colors.get("term15", "#EBDBB2")}'
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into alacritty.toml and fix import order
    home = os.path.expanduser("~")
    alacritty_conf = f"{home}/.config/alacritty/alacritty.toml"

    # Fix import order and migrate to [general] import (Alacritty 0.15+)
    if os.path.exists(alacritty_conf):
        modified, message = fix_alacritty_import_order(alacritty_conf)
        if modified:
            print(f"✓ Generated Alacritty config ({message})")
        else:
            print(f"✓ Generated Alacritty config ({message})")
    else:
        # Create new config with [general] import at top
        new_conf = (
            "# iNiR wallpaper theming\n"
            "[general]\n"
            'import = ["~/.config/alacritty/colors.toml"]\n'
        )
        Path(alacritty_conf).parent.mkdir(parents=True, exist_ok=True)
        Path(alacritty_conf).write_text(new_conf)
        print(f"✓ Generated Alacritty config and created new config file")


def generate_foot_config(colors, output_path):
    """Generate Foot terminal color config and auto-integrate"""
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

[colors]
foreground={colors.get("term7", "#A89984")[1:]}
background={colors.get("term0", "#282828")[1:]}

## Normal/regular colors (color palette 0-7)
regular0={colors.get("term0", "#282828")[1:]}  # black
regular1={colors.get("term1", "#CC241D")[1:]}  # red
regular2={colors.get("term2", "#98971A")[1:]}  # green
regular3={colors.get("term3", "#D79921")[1:]}  # yellow
regular4={colors.get("term4", "#458588")[1:]}  # blue
regular5={colors.get("term5", "#B16286")[1:]}  # magenta
regular6={colors.get("term6", "#689D6A")[1:]}  # cyan
regular7={colors.get("term7", "#A89984")[1:]}  # white

## Bright colors (color palette 8-15)
bright0={colors.get("term8", "#928374")[1:]}   # bright black
bright1={colors.get("term9", "#FB4934")[1:]}   # bright red
bright2={colors.get("term10", "#B8BB26")[1:]}  # bright green
bright3={colors.get("term11", "#FABD2F")[1:]}  # bright yellow
bright4={colors.get("term12", "#83A598")[1:]}  # bright blue
bright5={colors.get("term13", "#D3869B")[1:]}  # bright magenta
bright6={colors.get("term14", "#8EC07C")[1:]}  # bright cyan
bright7={colors.get("term15", "#EBDBB2")[1:]}  # bright white

## Cursor and selection colors
selection-foreground={colors.get("term0", "#282828")[1:]}
selection-background={colors.get("term7", "#A89984")[1:]}
jump-labels={colors.get("term0", "#282828")[1:]} {colors.get("term3", "#D79921")[1:]}
urls={colors.get("term4", "#458588")[1:]}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into foot.ini (add at the top to avoid section issues)
    home = os.path.expanduser("~")
    foot_conf = f"{home}/.config/foot/foot.ini"
    if ensure_line_in_file(
        foot_conf,
        "include=~/.config/foot/colors.ini",
        r"include\s*=.*colors\.ini",
        at_top=True,
    ):
        print(f"✓ Generated Foot config and auto-integrated")
    else:
        print(f"✓ Generated Foot config (already integrated)")


def generate_wezterm_config(colors, output_path):
    """Generate WezTerm terminal color config and auto-integrate"""
    config = f"""-- Auto-generated by ii wallpaper theming system
-- Do not edit manually - changes will be overwritten

return {{
  foreground = '{colors.get("term7", "#A89984")}',
  background = '{colors.get("term0", "#282828")}',
  
  cursor_bg = '{colors.get("term7", "#A89984")}',
  cursor_fg = '{colors.get("term0", "#282828")}',
  cursor_border = '{colors.get("term7", "#A89984")}',
  
  selection_fg = '{colors.get("term0", "#282828")}',
  selection_bg = '{colors.get("term7", "#A89984")}',
  
  scrollbar_thumb = '{colors.get("term8", "#928374")}',
  split = '{colors.get("term8", "#928374")}',
  
  ansi = {{
    '{colors.get("term0", "#282828")}',  -- black
    '{colors.get("term1", "#CC241D")}',  -- red
    '{colors.get("term2", "#98971A")}',  -- green
    '{colors.get("term3", "#D79921")}',  -- yellow
    '{colors.get("term4", "#458588")}',  -- blue
    '{colors.get("term5", "#B16286")}',  -- magenta
    '{colors.get("term6", "#689D6A")}',  -- cyan
    '{colors.get("term7", "#A89984")}',  -- white
  }},
  
  brights = {{
    '{colors.get("term8", "#928374")}',  -- bright black
    '{colors.get("term9", "#FB4934")}',  -- bright red
    '{colors.get("term10", "#B8BB26")}', -- bright green
    '{colors.get("term11", "#FABD2F")}', -- bright yellow
    '{colors.get("term12", "#83A598")}', -- bright blue
    '{colors.get("term13", "#D3869B")}', -- bright magenta
    '{colors.get("term14", "#8EC07C")}', -- bright cyan
    '{colors.get("term15", "#EBDBB2")}', -- bright white
  }},
  
  tab_bar = {{
    background = '{colors.get("term0", "#282828")}',
    active_tab = {{
      bg_color = '{colors.get("primary", "#458588")}',
      fg_color = '{colors.get("onPrimary", "#FFFFFF")}',
    }},
    inactive_tab = {{
      bg_color = '{colors.get("term8", "#928374")}',
      fg_color = '{colors.get("term7", "#A89984")}',
    }},
    inactive_tab_hover = {{
      bg_color = '{colors.get("term8", "#928374")}',
      fg_color = '{colors.get("term15", "#EBDBB2")}',
    }},
  }},
}}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into wezterm.lua
    home = os.path.expanduser("~")
    wezterm_conf = f"{home}/.config/wezterm/wezterm.lua"
    integration_code = """local wezterm = require('wezterm')
local config = wezterm.config_builder()
local colors = require('colors')
config.colors = colors
return config
"""

    wezterm_path = Path(wezterm_conf)
    if wezterm_path.exists():
        content = wezterm_path.read_text()
        if "require('colors')" not in content:
            # Add color loading to existing config
            lines = content.split("\n")
            # Find return config line and insert before it
            for i, line in enumerate(lines):
                if "return config" in line or "return {" in line:
                    lines.insert(i, "local colors = require('colors')")
                    lines.insert(i + 1, "config.colors = colors")
                    break
            wezterm_path.write_text("\n".join(lines))
            print(f"✓ Generated WezTerm config and auto-integrated")
        else:
            print(f"✓ Generated WezTerm config (already integrated)")
    else:
        wezterm_path.parent.mkdir(parents=True, exist_ok=True)
        wezterm_path.write_text(integration_code)
        print(f"✓ Generated WezTerm config and auto-integrated (created config)")


def generate_ghostty_config(colors, output_path):
    """Generate Ghostty terminal color config and auto-integrate"""
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten

background = {colors.get("term0", "#282828")}
foreground = {colors.get("term7", "#A89984")}

cursor-color = {colors.get("term7", "#A89984")}
cursor-text = {colors.get("term0", "#282828")}

selection-background = {colors.get("term7", "#A89984")}
selection-foreground = {colors.get("term0", "#282828")}

# Black
palette = 0={colors.get("term0", "#282828")}
palette = 8={colors.get("term8", "#928374")}

# Red
palette = 1={colors.get("term1", "#CC241D")}
palette = 9={colors.get("term9", "#FB4934")}

# Green
palette = 2={colors.get("term2", "#98971A")}
palette = 10={colors.get("term10", "#B8BB26")}

# Yellow
palette = 3={colors.get("term3", "#D79921")}
palette = 11={colors.get("term11", "#FABD2F")}

# Blue
palette = 4={colors.get("term4", "#458588")}
palette = 12={colors.get("term12", "#83A598")}

# Magenta
palette = 5={colors.get("term5", "#B16286")}
palette = 13={colors.get("term13", "#D3869B")}

# Cyan
palette = 6={colors.get("term6", "#689D6A")}
palette = 14={colors.get("term14", "#8EC07C")}

# White
palette = 7={colors.get("term7", "#A89984")}
palette = 15={colors.get("term15", "#EBDBB2")}
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into ghostty config
    home = os.path.expanduser("~")
    ghostty_conf = f"{home}/.config/ghostty/config"
    if ensure_line_in_file(ghostty_conf, "theme = ii-auto", r"theme\s*=\s*ii-auto"):
        print(f"✓ Generated Ghostty config and auto-integrated")
    else:
        print(f"✓ Generated Ghostty config (already integrated)")


def generate_konsole_config(colors, output_path):
    """Generate Konsole terminal color config"""
    config = f"""[Background]
Color={colors.get("term0", "#282828")[1:]}

[BackgroundIntense]
Color={colors.get("term0", "#282828")[1:]}

[Foreground]
Color={colors.get("term7", "#A89984")[1:]}

[ForegroundIntense]
Color={colors.get("term15", "#EBDBB2")[1:]}

[Color0]
Color={colors.get("term0", "#282828")[1:]}

[Color0Intense]
Color={colors.get("term8", "#928374")[1:]}

[Color1]
Color={colors.get("term1", "#CC241D")[1:]}

[Color1Intense]
Color={colors.get("term9", "#FB4934")[1:]}

[Color2]
Color={colors.get("term2", "#98971A")[1:]}

[Color2Intense]
Color={colors.get("term10", "#B8BB26")[1:]}

[Color3]
Color={colors.get("term3", "#D79921")[1:]}

[Color3Intense]
Color={colors.get("term11", "#FABD2F")[1:]}

[Color4]
Color={colors.get("term4", "#458588")[1:]}

[Color4Intense]
Color={colors.get("term12", "#83A598")[1:]}

[Color5]
Color={colors.get("term5", "#B16286")[1:]}

[Color5Intense]
Color={colors.get("term13", "#D3869B")[1:]}

[Color6]
Color={colors.get("term6", "#689D6A")[1:]}

[Color6Intense]
Color={colors.get("term14", "#8EC07C")[1:]}

[Color7]
Color={colors.get("term7", "#A89984")[1:]}

[Color7Intense]
Color={colors.get("term15", "#EBDBB2")[1:]}

[General]
Description=ii Auto-generated Theme
Opacity=1.0
Wallpaper=
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)
    print(f"✓ Generated Konsole config")


def generate_starship_config(colors, output_path):
    """Generate Starship prompt palette config and auto-integrate"""
    # Starship uses a TOML palette format
    config = f"""# Auto-generated by ii wallpaper theming system
# Do not edit manually - changes will be overwritten
# This file provides Material You colors to your Starship prompt

[palettes.ii]
primary = '{colors.get("primary", "#458588")}'
onPrimary = '{colors.get("onPrimary", "#FFFFFF")}'
secondary = '{colors.get("secondary", "#83A598")}'
onSecondary = '{colors.get("onSecondary", "#1D2021")}'
tertiary = '{colors.get("tertiary", "#D3869B")}'
onTertiary = '{colors.get("onTertiary", "#1D2021")}'
surface = '{colors.get("surface", "#1D2021")}'
onSurface = '{colors.get("onSurface", "#EBDBB2")}'
background = '{colors.get("term0", "#282828")}'
foreground = '{colors.get("term7", "#A89984")}'
black = '{colors.get("term0", "#282828")}'
red = '{colors.get("term1", "#CC241D")}'
green = '{colors.get("term2", "#98971A")}'
yellow = '{colors.get("term3", "#D79921")}'
blue = '{colors.get("term4", "#458588")}'
magenta = '{colors.get("term5", "#B16286")}'
cyan = '{colors.get("term6", "#689D6A")}'
white = '{colors.get("term7", "#A89984")}'
bright_black = '{colors.get("term8", "#928374")}'
bright_red = '{colors.get("term9", "#FB4934")}'
bright_green = '{colors.get("term10", "#B8BB26")}'
bright_yellow = '{colors.get("term11", "#FABD2F")}'
bright_blue = '{colors.get("term12", "#83A598")}'
bright_magenta = '{colors.get("term13", "#D3869B")}'
bright_cyan = '{colors.get("term14", "#8EC07C")}'
bright_white = '{colors.get("term15", "#EBDBB2")}'
"""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(config)

    # Auto-integrate into starship.toml
    home = os.path.expanduser("~")
    starship_conf = f"{home}/.config/starship.toml"

    # Check if starship.toml exists
    if os.path.exists(starship_conf):
        content = Path(starship_conf).read_text()

        # Check if palette_name is already set to ii
        if 'palette = "ii"' in content:
            print(f"✓ Generated Starship palette (already using ii palette)")
        else:
            # Add palette directive if not present
            if "palette =" not in content:
                # Add at top of file
                new_content = 'palette = "ii"\n\n' + content
                Path(starship_conf).write_text(new_content)
                print(f"✓ Generated Starship palette and set as active")
            else:
                print(
                    f"✓ Generated Starship palette (using different palette, change to 'palette = \"ii\"' to use)"
                )

        # Add source directive for palette file if not present
        palette_source = f'"$HOME/.config/starship/ii-palette.toml"'
        if palette_source not in content and "ii-palette.toml" not in content:
            # Prepend the source at the very top
            source_line = (
                f"# Import ii Material You palette\n# source = {palette_source}\n\n"
            )
            # Note: Starship doesn't support source/include, so we need to append the palette directly
            # We'll append the palette content to starship.toml if palettes.ii section doesn't exist
            if "[palettes.ii]" not in content:
                with open(starship_conf, "a") as f:
                    f.write("\n" + config)
                print(f"  → Appended ii palette to starship.toml")
    else:
        print(
            f"✓ Generated Starship palette (starship.toml not found - create it and add 'palette = \"ii\"')"
        )


def main():
    parser = argparse.ArgumentParser(
        description="Generate terminal color configs from material_colors.scss"
    )
    parser.add_argument(
        "--scss",
        type=str,
        default=os.path.expanduser(
            "~/.local/state/quickshell/user/generated/material_colors.scss"
        ),
        help="Path to material_colors.scss file",
    )
    parser.add_argument(
        "--terminals",
        type=str,
        nargs="+",
        choices=[
            "kitty",
            "alacritty",
            "foot",
            "wezterm",
            "ghostty",
            "konsole",
            "starship",
            "all",
        ],
        default=["all"],
        help="Which terminals to generate configs for",
    )

    args = parser.parse_args()

    # Parse colors from SCSS
    colors = parse_scss_colors(args.scss)

    if not colors:
        print("Error: No colors found in SCSS file", file=sys.stderr)
        sys.exit(1)

    home = os.path.expanduser("~")
    terminals = (
        args.terminals
        if "all" not in args.terminals
        else ["kitty", "alacritty", "foot", "wezterm", "ghostty", "konsole", "starship"]
    )

    # Generate configs for requested terminals
    if "kitty" in terminals:
        generate_kitty_config(colors, f"{home}/.config/kitty/current-theme.conf")

    if "alacritty" in terminals:
        generate_alacritty_config(colors, f"{home}/.config/alacritty/colors.toml")

    if "foot" in terminals:
        generate_foot_config(colors, f"{home}/.config/foot/colors.ini")

    if "wezterm" in terminals:
        generate_wezterm_config(colors, f"{home}/.config/wezterm/colors.lua")

    if "ghostty" in terminals:
        generate_ghostty_config(colors, f"{home}/.config/ghostty/themes/ii-auto")

    if "konsole" in terminals:
        generate_konsole_config(
            colors, f"{home}/.local/share/konsole/ii-auto.colorscheme"
        )

    if "starship" in terminals:
        generate_starship_config(colors, f"{home}/.config/starship/ii-palette.toml")


if __name__ == "__main__":
    main()
