pragma Singleton
pragma ComponentBehavior: Bound

import QtQuick
import qs.modules.common
import qs.modules.iris.style
import qs.modules.iris.pieces

QtObject {
    id: root

    function plain(value: var): var {
        if (value === null || value === undefined || typeof value !== "object") return value
        if (value.length !== undefined && typeof value !== "string") return Array.from(value, item => root.plain(item))
        const out = {}
        for (const key of Object.keys(value)) out[key] = root.plain(value[key])
        return out
    }
    function same(a: var, b: var): bool {
        return JSON.stringify(root.plain(a)) === JSON.stringify(root.plain(b))
    }

    readonly property var studio: [
        { target: "material", group: "Material", label: "Material", description: "What every surface is made of. Raised steps, fills and the frame follow it.", path: "iris.appearance.theme.surface", kind: "choice", fallback: "black", choices: [{label:"Black",value:"black",swatch:IrisStyle.materialSwatch("black")},{label:"Graphite",value:"graphite",swatch:IrisStyle.materialSwatch("graphite")},{label:"Midnight",value:"midnight",swatch:IrisStyle.materialSwatch("midnight")},{label:"Wallpaper",value:"wallpaper",swatch:IrisStyle.materialSwatch("wallpaper")},{label:"Theme",value:"theme",swatch:IrisStyle.materialSwatch("theme")}] },
        { target: "material", group: "Adaptive", label: "Adapt to the wallpaper", description: "Reads the wallpaper's brightness, contrast and colour and shapes iRiS from it: calmer images round corners and soften shadows, busy or bright ones sharpen and firm up lines, colourful ones carry more light. 0 keeps your values exactly.", path: "iris.appearance.adaptive", kind: "range", fallback: 0, min: 0, max: 100, step: 5, unit: " %" },
        { target: "material", group: "Material", label: "Fills", description: "Groups, tracks, hovered and pressed controls.", path: "iris.appearance.theme.fill", kind: "range", fallback: 100, min: 30, max: 200, step: 5, unit: " %" },
        { target: "material", group: "Material", label: "Lines", description: "Hairlines and borders. 0 removes them.", path: "iris.appearance.theme.lines", kind: "range", fallback: 100, min: 0, max: 200, step: 5, unit: " %" },
        { target: "material", group: "Material", label: "Shadows", description: "Under bodies floating over windows.", path: "iris.appearance.theme.shadow", kind: "range", fallback: 100, min: 0, max: 160, step: 5, unit: " %" },
        { target: "material", group: "Material", label: "Outline", description: "A hairline around every silhouette, so black holds over dark windows.", path: "iris.appearance.theme.rim", kind: "switch", fallback: true },
        { target: "material", group: "Material", label: "Outline colour", path: "iris.appearance.theme.rimTint", visibleWhen: "iris.appearance.theme.rim", kind: "choice", fallback: "neutral", choices: [{label:"Neutral",value:"neutral"},{label:"Accent",value:"accent"},{label:"Highlight",value:"highlight"}] },
        { target: "material", group: "Material", label: "Outline width", path: "iris.appearance.theme.rimWidth", visibleWhen: "iris.appearance.theme.rim", kind: "range", fallback: 1, min: 1, max: 3, unit: " px" },
        { target: "material", group: "Glass", label: "Glass", description: "Every iRiS surface becomes glass over the blurred wallpaper. Blur is under construction: Niri blurs the windows below too (26.04+), but many surfaces don't follow it yet.", path: "iris.appearance.glass.mode", kind: "choice", fallback: "off", choices: [{label:"Off",value:"off",glyph:"crop_square"},{label:"Glass",value:"wallpaper",glyph:"blur_on"},{label:"Blur (beta)",value:"compositor",glyph:"lens_blur"}] },
        { target: "material", group: "Glass", label: "Tint", description: "How much of the material stays over the glass. iRiS raises it on bright wallpapers so text stays legible.", path: "iris.appearance.glass.tint", kind: "range", fallback: 58, min: 12, max: 96, step: 2, unit: " %" },
        { target: "material", group: "Glass", label: "Frost", description: "How blurred the wallpaper is behind the glass.", path: "iris.appearance.glass.blur", visibleWhen: "iris.appearance.glass.mode=wallpaper", kind: "range", fallback: 100, min: 20, max: 100, step: 5, unit: " %" },
        { target: "material", group: "Shape", label: "Corners", description: "Every radius in the family; nested corners keep stepping down.", path: "iris.appearance.theme.shape", kind: "range", fallback: 100, min: 30, max: 160, step: 5, unit: " %" },
        { target: "material", group: "Shape", label: "Fusion", description: "How deeply shapes melt where they meet. 0 keeps crisp joins.", path: "iris.appearance.theme.melt", kind: "range", fallback: 0, min: 0, max: 200, step: 5, unit: " %" },
        { target: "material", group: "Shape", label: "Spacing", description: "Padding, gaps and control sizes.", path: "iris.appearance.density", kind: "range", fallback: 1, min: 0.8, max: 1.35, step: 0.05, unit: "×" },
        { target: "material", group: "Frame", label: "Close the shell around the screen", description: "One black band on every edge, with the screen's corners turned inward. Windows and the Island sit inside it.", path: "iris.surround.enable", kind: "switch", fallback: true },
        { target: "material", group: "Frame", label: "Frame width", path: "iris.surround.thickness", visibleWhen: "iris.surround.enable", kind: "range", fallback: 10, min: 4, max: 28, unit: " px" },
        { target: "material", group: "Frame", label: "Screen corners", description: "How round the frame turns inward at the corners of the screen.", path: "iris.surround.radius", visibleWhen: "iris.surround.enable", kind: "range", fallback: 22, min: 0, max: 44, unit: " px" },
        { target: "material", group: "Frame", label: "Music on the edges", description: "Organic Edge: its own flowing wave beside the frame, or the frame itself swelling with the bass.", path: "background.edgeWidgets.organic.enable", visibleWhen: "iris.surround.enable", kind: "switch", fallback: false },
        { target: "material", group: "Frame", label: "Music drives", path: "iris.surround.music", visibleWhen: "background.edgeWidgets.organic.enable", kind: "choice", fallback: "widget", choices: [{label:"The wave",value:"widget"},{label:"The frame",value:"frame"}] },
        { target: "material", group: "Frame", label: "Band", description: "How thick the edge is.", path: "iris.surround.thickness", visibleWhen: "iris.surround.enable", kind: "range", fallback: 10, min: 2, max: 40, unit: " px" },
        { target: "material", group: "Frame", label: "Inner corners", description: "How far the corners turn inward.", path: "iris.surround.radius", visibleWhen: "iris.surround.enable", kind: "range", fallback: 22, min: 0, max: 64, unit: " px" },
        { target: "colour", group: "Accent", label: "System accent", description: "Selection and controls across iRiS. Activity colours keep their identity.", path: "iris.appearance.accent", kind: "choice", fallback: "blue", choices: [{label:"Blue",value:"blue",swatch:IrisStyle.accents.blue},{label:"Mint",value:"mint",swatch:IrisStyle.accents.mint},{label:"Rose",value:"rose",swatch:IrisStyle.accents.rose},{label:"Lilac",value:"lilac",swatch:IrisStyle.accents.lilac},{label:"Theme",value:"theme",swatch:IrisStyle.themeAccent},{label:"Wallpaper",value:"wallpaper"},{label:"Custom",value:"custom"}] },
        { target: "colour", group: "Accent", label: "Accent hue", visibleWhen: "iris.appearance.accent=custom", path: "iris.appearance.theme.accentHue", kind: "hue", fallback: 212 },
        { target: "colour", group: "Highlight", label: "Highlight", description: "The glanced detail: clock separator, day number, timers.", path: "iris.appearance.highlight", kind: "choice", fallback: "orange", choices: [{label:"Orange",value:"orange",swatch:IrisStyle.highlights.orange},{label:"Yellow",value:"yellow",swatch:IrisStyle.highlights.yellow},{label:"Red",value:"red",swatch:IrisStyle.highlights.red},{label:"Pink",value:"pink",swatch:IrisStyle.highlights.pink},{label:"Green",value:"green",swatch:IrisStyle.highlights.green},{label:"Accent",value:"accent"},{label:"Theme",value:"theme",swatch:IrisStyle.vividHighlight(Appearance.colors.colTertiary, IrisStyle.highlights.orange)},{label:"Wallpaper",value:"wallpaper"},{label:"Custom",value:"custom"}] },
        { target: "colour", group: "Highlight", label: "Highlight hue", visibleWhen: "iris.appearance.highlight=custom", path: "iris.appearance.theme.highlightHue", kind: "hue", fallback: 32 },
        { target: "colour", group: "Badges", label: "Unread counts", description: "The family's red, your accent, the highlight, or a quiet neutral.", path: "iris.appearance.theme.badge", kind: "choice", fallback: "alert", choices: [{label:"Alert",value:"alert",swatch:IrisStyle.identity.red},{label:"Accent",value:"accent"},{label:"Highlight",value:"highlight",swatch:IrisStyle.secondaryAccent},{label:"Neutral",value:"neutral",swatch:IrisStyle.surfaceHighestOpaque}] },
        { target: "colour", group: "Light", label: "Light", description: "What an open card or panel is lit by: its own colour — the sky for weather, the highlight for timers — or the wallpaper's. It pours in from where the body grew.", path: "iris.appearance.aura", kind: "choice", fallback: "subtle", choices: [{label:"Off",value:"off",glyph:"light_off"},{label:"Subtle",value:"subtle",glyph:"light_mode"},{label:"Vivid",value:"vivid",glyph:"wb_sunny"}] },
        { target: "colour", group: "Light", label: "Reach", description: "How far the light goes into a body: just its head, or deeper.", path: "iris.appearance.theme.lightReach", kind: "range", fallback: 100, min: 50, max: 300, step: 5, unit: " %" },
        { target: "colour", group: "Light", label: "Glow", description: "Bodies that float over your windows (cards, Spotlight, banners, the Dock menu) cast a halo in the accent colour instead of a dark shadow.", path: "iris.appearance.theme.glow", kind: "range", fallback: 0, min: 0, max: 100, step: 5, unit: " %" },
        { target: "colour", group: "Wallpaper", label: "Wallpaper tint", description: "How much of the wallpaper the black carries. The Island stays black; raised surfaces and fills take the trace.", path: "iris.appearance.tint", kind: "range", fallback: 0, min: 0, max: 100, step: 5, unit: "%" },
        { target: "type", group: "Text", label: "Size", description: "Text across iRiS, on top of the system scale.", path: "iris.appearance.theme.text", kind: "range", fallback: 100, min: 85, max: 125, step: 5, unit: " %" },
        { target: "type", group: "Text", label: "Contrast", description: "Secondary and quiet text.", path: "iris.appearance.theme.contrast", kind: "range", fallback: 100, min: 60, max: 150, step: 5, unit: " %" },
        { target: "type", group: "Faces", label: "Text", path: "iris.appearance.fontFamily", kind: "choice", previewFont: true, fallback: "", choices: [{label:"Noto Sans",value:""},{label:"Rubik",value:"Rubik"},{label:"Readex Pro",value:"Readex Pro"},{label:"Roboto Flex",value:"Roboto Flex"},{label:"Gabarito",value:"Gabarito"},{label:"Space Grotesk",value:"Space Grotesk"},{label:"Oxanium",value:"Oxanium"},{label:"JetBrains Mono",value:"JetBrainsMono Nerd Font"}] },
        { target: "type", group: "Faces", label: "Titles", path: "iris.appearance.titleFontFamily", kind: "choice", previewFont: true, fallback: "", choices: [{label:"Readex Pro",value:""},{label:"Noto Sans",value:"Noto Sans"},{label:"Rubik",value:"Rubik"},{label:"Roboto Flex",value:"Roboto Flex"},{label:"Gabarito",value:"Gabarito"},{label:"Space Grotesk",value:"Space Grotesk"},{label:"Oxanium",value:"Oxanium"},{label:"JetBrains Mono",value:"JetBrainsMono Nerd Font"}] },
        { target: "type", group: "Faces", label: "Figures", description: "Clocks, timers and levels.", path: "iris.appearance.numbersFontFamily", kind: "choice", previewFont: true, fallback: "", choices: [{label:"Rubik",value:""},{label:"Noto Sans",value:"Noto Sans"},{label:"Readex Pro",value:"Readex Pro"},{label:"Roboto Flex",value:"Roboto Flex"},{label:"Gabarito",value:"Gabarito"},{label:"Space Grotesk",value:"Space Grotesk"},{label:"Oxanium",value:"Oxanium"},{label:"JetBrains Mono",value:"JetBrainsMono Nerd Font"}] },
        { target: "type", group: "Faces", label: "Figure weight", path: "iris.appearance.figureWeight", kind: "choice", fallback: "bold", choices: [{label:"Light",value:"light"},{label:"Regular",value:"regular"},{label:"Bold",value:"bold"}] },
        { target: "motion", group: "Motion", label: "Movement", description: "How every shape iRiS grows moves. Direct is the iRiS motion: fast out, settles without bouncing. Liquid and Elastic are springs with a settle or a bounce, Glide is slow and even, Snap is terse.", path: "iris.appearance.morph", kind: "choice", fallback: "direct", choices: [{label:"Direct",value:"direct",glyph:"north_east"},{label:"Liquid",value:"liquid",glyph:"water_drop"},{label:"Glide",value:"glide",glyph:"swipe_right_alt"},{label:"Snap",value:"snap",glyph:"bolt"},{label:"Elastic",value:"elastic",glyph:"airwave"}] },
        { target: "motion", group: "Curve", label: "Curve", visibleWhen: "iris.appearance.motion", description: "The path a Direct shape follows as it opens or adjusts; closing is always absorbed back into its origin. Expressive leaves fast and lands softly; Standard is even; Gentle eases in and out; Swift is short and sharp.", path: "iris.appearance.theme.curve", kind: "choice", fallback: "expressive", choices: [{label:"Expressive",value:"expressive",glyph:"north_east"},{label:"Standard",value:"standard",glyph:"trending_up"},{label:"Gentle",value:"gentle",glyph:"moving"},{label:"Swift",value:"swift",glyph:"bolt"},{label:"Custom",value:"custom",glyph:"draw"}] },
        { target: "motion", group: "Curve", label: "Shape", visibleWhen: "iris.appearance.motion", description: "Drag the two handles. The curve becomes Custom.", path: "iris.appearance.theme.curvePoints", kind: "curve", fallback: [0.16, 1, 0.3, 1] },
        { target: "motion", group: "Timing", label: "Open and close", visibleWhen: "iris.appearance.motion", description: "How long a shape takes to grow out of what opened it and fold back.", path: "iris.appearance.theme.openTime", kind: "range", fallback: 100, min: 40, max: 250, step: 5, unit: " %" },
        { target: "motion", group: "Timing", label: "Adjusting", visibleWhen: "iris.appearance.motion", description: "How long an open shape takes to change size, like switching pages.", path: "iris.appearance.theme.moveTime", kind: "range", fallback: 100, min: 40, max: 250, step: 5, unit: " %" },
        { target: "motion", group: "Timing", label: "Content arrives", visibleWhen: "iris.appearance.motion", description: "Lower shows what is inside while the shape is still growing; higher waits until it has formed.", path: "iris.appearance.theme.contentTiming", kind: "range", fallback: 100, min: 30, max: 170, step: 5, unit: " %" },
        { target: "motion", group: "Per surface", label: "Island", visibleWhen: "iris.appearance.motion", description: "Speed of this surface's morph. 100 % follows the timing above.", path: "iris.appearance.surfaces.island.speed", kind: "range", fallback: 100, min: 40, max: 250, step: 5, unit: " %" },
        { target: "motion", group: "Per surface", label: "Cards", visibleWhen: "iris.appearance.motion", path: "iris.appearance.surfaces.cards.speed", kind: "range", fallback: 100, min: 40, max: 250, step: 5, unit: " %" },
        { target: "motion", group: "Per surface", label: "Control Center", visibleWhen: "iris.appearance.motion", path: "iris.appearance.surfaces.controlCenter.speed", kind: "range", fallback: 100, min: 40, max: 250, step: 5, unit: " %" },
        { target: "motion", group: "Per surface", label: "Side panels", visibleWhen: "iris.appearance.motion", path: "iris.appearance.surfaces.panels.speed", kind: "range", fallback: 100, min: 40, max: 250, step: 5, unit: " %" },
        { target: "motion", group: "Per surface", label: "Spotlight", visibleWhen: "iris.appearance.motion", path: "iris.appearance.surfaces.spotlight.speed", kind: "range", fallback: 100, min: 40, max: 250, step: 5, unit: " %" },
        { target: "motion", group: "Per surface", label: "Settings and Studio", visibleWhen: "iris.appearance.motion", path: "iris.appearance.surfaces.settings.speed", kind: "range", fallback: 100, min: 40, max: 250, step: 5, unit: " %" },
        { target: "motion", group: "Per surface", label: "Menus", visibleWhen: "iris.appearance.motion", path: "iris.appearance.surfaces.menus.speed", kind: "range", fallback: 100, min: 40, max: 250, step: 5, unit: " %" },
        { target: "motion", group: "Per surface", label: "Wallpaper gallery", visibleWhen: "iris.appearance.motion", path: "iris.appearance.surfaces.gallery.speed", kind: "range", fallback: 100, min: 40, max: 250, step: 5, unit: " %" },
        { target: "motion", group: "Touch", label: "Press depth", description: "How far buttons, bubbles and the Island dip under a press. 0 keeps them still.", path: "iris.appearance.theme.press", kind: "range", fallback: 100, min: 0, max: 200, step: 10, unit: " %" },
        { target: "motion", group: "Motion", label: "Duration", visibleWhen: "iris.appearance.motion", description: "How long a shape takes to grow out of what opened it.", path: "iris.appearance.motionDuration", kind: "range", fallback:220,min:100,max:400,step:10,unit:" ms" },
        { target: "motion", group: "Motion", label: "Bounce", visibleWhen: "iris.appearance.motion", description: "How far arrivals and moves pass their place before settling, as a share of the style's own. 0 never bounces; leaving never does.", path: "iris.appearance.theme.bounce", kind: "range", fallback: 100, min: 0, max: 200, step: 10, unit: " %" },
        { target: "island", group: "Shape", label: "Island layout", description: "Hug its content in the middle, hug one end, or span the whole edge as a bar.", path: "iris.bar.layout", kind: "choice", fallback: "island", choices: [{label:"Island",value:"island",glyph:"pill"},{label:"Left",value:"left",glyph:"align_horizontal_left"},{label:"Right",value:"right",glyph:"align_horizontal_right"},{label:"Full width",value:"full",glyph:"width_full"}] },
        { target: "island", group: "Shape", label: "Screen edge", path: "iris.bar.position", kind: "choice", fallback: "top", choices: [{label:"Top",value:"top",glyph:"vertical_align_top"},{label:"Bottom",value:"bottom",glyph:"vertical_align_bottom"},{label:"Left",value:"left",glyph:"align_horizontal_left"},{label:"Right",value:"right",glyph:"align_horizontal_right"}] },
        { target: "island", group: "Shape", label: "Height", description: "The resting Island, and how deep its notch melts into the edge.", path: "iris.bar.height", kind: "range", fallback: 42, min: 32, max: 64, unit: " px" },
        { target: "island", group: "Shape", label: "Attach as a notch", description: "Melts the Island into the screen edge.", path: "iris.bar.notch", kind: "switch", fallback: true },
        { target: "island", group: "Shape", label: "Notch curve", visibleWhen: "iris.bar.notch", description: "How wide the shoulders are where the Island turns into its edge.", path: "iris.bar.notchCurve", kind: "range", fallback: 100, min: 20, max: 200, step: 5, unit: " %" },
        { target: "island", group: "Shape", label: "Bubble gap", description: "How far the bubbles beside the Island rest from it.", path: "iris.bar.satelliteGap", kind: "range", fallback: 6, min: 0, max: 24, unit: " px" },
        { target: "island", group: "Shape", label: "Height", path: "iris.bar.height", kind: "range", fallback:42,min:32,max:64,unit:" px" },
        { target: "island", group: "Shape", label: "Gap from the edge", path: "iris.bar.margin", kind: "range", fallback:8,min:0,max:24,unit:" px" },
        { target: "island", group: "Shape", label: "Expanded corners", path: "iris.appearance.expandedRadius", kind: "range", fallback:28,min:16,max:40,unit:" px" },
        { target: "island", group: "At rest", label: "Clock", description: "What the resting Island shows beside the time.", path: "iris.bar.clockStyle", kind: "choice", fallback: "dateTime", choices: [{label:"Time",value:"time"},{label:"Date",value:"dateTime"},{label:"Weather",value:"weather"}] },
        { target: "island", group: "At rest", label: "Utility island", description: "Emerges beside the Island; the tray hides when no apps are present.", path: "iris.bar.auxiliary", kind: "choice", fallback: "tray", choices: [{label:"Tray",value:"tray"},{label:"Timers",value:"tools"},{label:"Sound",value:"sound"},{label:"Microphone",value:"mic"},{label:"None",value:"none"}] },
        { target: "island", group: "At rest", label: "Clock size", description: "The time and date on the resting Island. The Island grows to fit them.", path: "iris.bar.clockScale", kind: "range", fallback: 100, min: 80, max: 150, step: 5, unit: " %" },
        { target: "island", group: "At rest", label: "Clock accent", description: "The colour of the time's separator and the day number on the resting Island.", path: "iris.bar.clockAccent", kind: "choice", fallback: "highlight", choices: [{label:"Highlight",value:"highlight",swatch:IrisStyle.secondaryAccent},{label:"Accent",value:"accent",swatch:IrisStyle.accent},{label:"Plain",value:"plain",swatch:IrisStyle.text}] },
        { target: "island", group: "At rest", label: "Breathing room", description: "Space around what the resting Island shows.", path: "iris.bar.padding", kind: "range", fallback: 100, min: 50, max: 250, step: 10, unit: " %" },
        { target: "island", group: "At rest", label: "Bubble size", description: "The bubbles beside the Island, as a share of its height.", path: "iris.bar.satelliteScale", kind: "range", fallback: 100, min: 70, max: 100, step: 5, unit: " %" },
        { target: "island", group: "Desktop page", label: "Header", description: "What sits behind the time when the Island shows your desktop.", path: "iris.bar.desktopBanner", kind: "choice", fallback: "wallpaper", choices: [{label:"Wallpaper",value:"wallpaper"},{label:"None",value:"none"}] },
        { target: "island", group: "Desktop page", label: "Blocks", description: "What sits under the time, in the order you switch them on. You can also arrange them on the Island itself: open its desktop page and tap the pencil.", path: "iris.bar.desktopBlocks", kind: "pieces", fallback: ["profile", "context", "forecast", "agenda", "modules"], choices: [{label:"Profile",value:"profile"},{label:"Current app",value:"context"},{label:"Forecast",value:"forecast"},{label:"Up next",value:"agenda"},{label:"Vitals",value:"vitals"},{label:"Modules",value:"modules"}] },
        { target: "island", group: "Desktop page", label: "Block style", description: "Plain rows sit on the Island's black like the rest of the page; Grouped puts the forecast and vitals strips on quiet plates.", path: "iris.bar.blockStyle", kind: "choice", fallback: "plain", choices: [{label:"Plain",value:"plain",glyph:"view_agenda"},{label:"Grouped",value:"grouped",glyph:"splitscreen"}] },
        { target: "island", group: "Pages", label: "Page width", description: "How wide the open Island is. The activity page keeps its proportion.", path: "iris.bar.pageWidth", kind: "range", fallback: 440, min: 360, max: 600, step: 10, unit: " px" },
        { target: "island", group: "Pages", label: "Navigation", description: "What the open Island's navigation row offers, in the order you switch them on. Pages come first; scroll over the row, or swipe sideways anywhere on the open Island, to move between them.", path: "iris.bar.navItems", kind: "pieces", fallback: ["media", "activity", "desktop", "tray", "tools", "focus", "today", "controls", "settings"], choices: [{label:"Now playing",value:"media"},{label:"Live activities",value:"activity"},{label:"Desktop",value:"desktop"},{label:"Tray",value:"tray"},{label:"Timers",value:"tools"},{label:"Focus panel",value:"focus"},{label:"Today panel",value:"today"},{label:"Quick controls",value:"controls"},{label:"Settings",value:"settings"}] },
        { target: "island", group: "Player page", label: "Blocks", description: "What the player page shows, in the order you switch them on.", path: "iris.bar.mediaBlocks", kind: "pieces", fallback: ["player", "timeline", "transport", "players", "levels"], choices: [{label:"Now playing",value:"player"},{label:"Timeline",value:"timeline"},{label:"Controls",value:"transport"},{label:"Other players",value:"players"},{label:"App volume",value:"levels"}] },
        { target: "pieces", group: "Size", label: "Bubble size", description: "Bubbles off the Island, as a share of the Island's height.", path: "iris.bubbles.scale", kind: "range", fallback: 100, min: 60, max: 140, step: 5, unit: " %" },
        { target: "pieces", group: "Size", label: "Shape", description: "The profile of every bubble, bar and satellite. Circles are the Island's own; squircles and squares read like app tiles.", path: "iris.appearance.theme.pieceShape", kind: "choice", fallback: "circle", choices: [{label:"Circle",value:"circle",glyph:"circle"},{label:"Squircle",value:"squircle",glyph:"crop_square"},{label:"Square",value:"square",glyph:"square"}] },
        { target: "pieces", group: "On the contour", label: "Group into a bar", description: "Bubbles resting in the same place share one plate and read as a small bar; off, each one floats as its own disc.", path: "iris.bubbles.cluster", kind: "switch", fallback: true },
        { target: "pieces", group: "On the contour", label: "Keep them on the frame", description: "Bubbles in a corner or on an edge sit on the shell's own edge, where they read as a swelling of it, instead of floating over your windows.", path: "iris.bubbles.attach", kind: "switch", fallback: true },
        { target: "pieces", group: "On the contour", label: "Meet the edge", description: "Notch: they melt into the edge with the Island's curved shoulders. Weld: they touch it. Gap: they keep the Island's margin from it.", path: "iris.bubbles.join", visibleWhen: "iris.bubbles.attach", kind: "choice", fallback: "notch", choices: [{label:"Notch",value:"notch"},{label:"Weld",value:"weld"},{label:"Gap",value:"gap"}] },
        { target: "pieces", group: "On the contour", label: "Shoulders", description: "How deep the curve is where a bubble melts into the edge.", path: "iris.bubbles.notchCurve", visibleWhen: "iris.bubbles.join=notch", kind: "range", fallback: 100, min: 30, max: 200, step: 5, unit: " %" },
        { target: "pieces", group: "Opening bodies", label: "Join to opener", description: "When settled, let a card or Control Center become one silhouette with the bubble or Island that opened it.", path: "iris.appearance.surfaces.cards.joinOrigin", kind: "switch", fallback: true },
        { target: "bodies", group: "Cards", label: "Corners", description: "Auto keeps the family's shape for cards.", path: "iris.appearance.surfaces.cards.radius", kind: "range", fallback: 0, min: 0, max: 44, unit: " px", zeroLabel: "Auto" },
        { target: "bodies", group: "Joining", label: "Opens", description: "Where a card or the Control Center grows from a bubble: away from the edge it sits on, or along it.", path: "iris.appearance.theme.placement", kind: "choice", fallback: "auto", choices: [{label:"Away from the edge",value:"auto",glyph:"open_in_new"},{label:"Along the edge",value:"along",glyph:"swap_vert"}] },
        { target: "bodies", group: "Joining", label: "Air", description: "The space between what opened and the bar or bubble it came from.", path: "iris.appearance.theme.air", kind: "range", fallback: 8, min: 0, max: 40, unit: " px" },
        { target: "bodies", group: "Joining", label: "Fusion", description: "How deeply bodies melt where they touch. 0 keeps joins crisp; the join to a bubble and the notch keep their own shape.", path: "iris.appearance.theme.melt", kind: "range", fallback: 0, min: 0, max: 200, step: 5, unit: " %" },
        { target: "bodies", group: "Cards", label: "Width", description: "Auto keeps the family's width.", path: "iris.appearance.surfaces.cards.width", kind: "range", fallback: 0, min: 0, max: 560, step: 10, unit: " px", zeroLabel: "Auto" },
        { target: "bodies", group: "Cards", label: "Light", description: "Its own colour, the wallpaper's, or plain black.", path: "iris.appearance.surfaces.cards.light", kind: "choice", fallback: "inherit", choices: [{label:"Own",value:"inherit",glyph:"auto_awesome"},{label:"Wallpaper",value:"wallpaper",glyph:"wallpaper"},{label:"Off",value:"off",glyph:"light_off"}] },
        { target: "bodies", group: "Card contents", label: "Header", description: "The glyph, name and figure at the top of the sound and microphone cards.", path: "iris.appearance.surfaces.cards.header", kind: "switch", fallback: true },
        { target: "bodies", group: "Card contents", label: "Devices", description: "Pick the output or input right inside the card.", path: "iris.appearance.surfaces.cards.devices", kind: "switch", fallback: true },
        { target: "bodies", group: "Card contents", label: "App volumes", description: "Each app's level under the sound card.", path: "iris.appearance.surfaces.cards.mixer", kind: "switch", fallback: true },
        { target: "bodies", group: "Control Center", label: "Corners", description: "Auto keeps the family's shape for the panel.", path: "iris.appearance.surfaces.controlCenter.radius", kind: "range", fallback: 0, min: 0, max: 44, unit: " px", zeroLabel: "Auto" },
        { target: "bodies", group: "Control Center", label: "Light", description: "Its own colour, the wallpaper's, or plain black.", path: "iris.appearance.surfaces.controlCenter.light", kind: "choice", fallback: "inherit", choices: [{label:"Own",value:"inherit",glyph:"auto_awesome"},{label:"Wallpaper",value:"wallpaper",glyph:"wallpaper"},{label:"Off",value:"off",glyph:"light_off"}] },
        { target: "bodies", group: "Control Center", label: "Sections", description: "What the panel shows, in the order you switch them on. Connectivity and music share a row, and so do shortcuts and levels.", path: "iris.controlCenter.sections", kind: "pieces", fallback: ["connectivity", "media", "shortcuts", "levels", "notifications"], choices: [{label:"Connectivity",value:"connectivity"},{label:"Music",value:"media"},{label:"Shortcuts",value:"shortcuts"},{label:"Levels",value:"levels"},{label:"Notifications",value:"notifications"}] },
        { target: "bodies", group: "Control Center", label: "Quick actions", description: "Tiles are wide glyph plates on the panel; Round makes them the same body as the connectivity toggles.", path: "iris.controlCenter.controls", kind: "choice", fallback: "tiles", choices: [{label:"Tiles",value:"tiles",glyph:"grid_view"},{label:"Round",value:"round",glyph:"radio_button_checked"}] },
        { target: "bodies", group: "Control Center", label: "Opens as", description: "The Island itself becomes the Control Center, or a panel hangs from it. From a bubble it always grows beside that bubble.", path: "iris.controlCenter.opens", kind: "choice", fallback: "island", choices: [{label:"The Island",value:"island",glyph:"pill"},{label:"A panel",value:"panel",glyph:"web_asset"}] },
        { target: "bodies", group: "Control Center", label: "Width", path: "iris.controlCenter.width", kind: "range", fallback:360,min:320,max:540,step:10,unit:" px" },
        { target: "bodies", group: "Player", label: "Round album cover", path: "iris.player.roundCover", kind: "switch", fallback:true },
        { target: "bodies", group: "Player", label: "Blurred album background", description: "Tints the expanded Island and media cards with the cover.", path: "iris.player.artworkBackground", kind: "switch", fallback:true },
        { target: "places", group: "Side panels", label: "Corners", description: "Auto keeps the family's shape for side panels.", path: "iris.appearance.surfaces.panels.radius", kind: "range", fallback: 0, min: 0, max: 44, unit: " px", zeroLabel: "Auto" },
        { target: "places", group: "Side panels", label: "Light", description: "Its own colour, the wallpaper's, or plain black.", path: "iris.appearance.surfaces.panels.light", kind: "choice", fallback: "inherit", choices: [{label:"Own",value:"inherit",glyph:"auto_awesome"},{label:"Wallpaper",value:"wallpaper",glyph:"wallpaper"},{label:"Off",value:"off",glyph:"light_off"}] },
        { target: "places", group: "Spotlight", label: "Corners", description: "Auto keeps the family's shape for Spotlight.", path: "iris.appearance.surfaces.spotlight.radius", kind: "range", fallback: 0, min: 0, max: 44, unit: " px", zeroLabel: "Auto" },
        { target: "places", group: "Spotlight", label: "Light", description: "Its own colour, the wallpaper's, or plain black.", path: "iris.appearance.surfaces.spotlight.light", kind: "choice", fallback: "inherit", choices: [{label:"Own",value:"inherit",glyph:"auto_awesome"},{label:"Wallpaper",value:"wallpaper",glyph:"wallpaper"},{label:"Off",value:"off",glyph:"light_off"}] },
        { target: "places", group: "Spotlight", label: "Opens from", description: "Floating grows out of the Island into a sheet of its own; The Island makes the Island itself become Spotlight, joined to its edge, with the search field on the Island's side.", path: "iris.palette.opens", kind: "choice", fallback: "floating", choices: [{label:"Floating",value:"floating",glyph:"web_asset"},{label:"The Island",value:"island",glyph:"pill"}] },
        { target: "places", group: "Spotlight", label: "Width", path: "iris.palette.width", kind: "range", fallback:640,min:420,max:900,step:10,unit:" px" },
        { target: "places", group: "Wallpaper gallery", label: "Corners", description: "Auto keeps the family's shape for the gallery.", path: "iris.appearance.surfaces.gallery.radius", kind: "range", fallback: 0, min: 0, max: 44, unit: " px", zeroLabel: "Auto" },
        { target: "places", group: "Wallpaper gallery", label: "Light", description: "Its own colour, the wallpaper's, or plain black.", path: "iris.appearance.surfaces.gallery.light", kind: "choice", fallback: "inherit", choices: [{label:"Own",value:"inherit",glyph:"auto_awesome"},{label:"Wallpaper",value:"wallpaper",glyph:"wallpaper"},{label:"Off",value:"off",glyph:"light_off"}] },
        { target: "places", group: "Wallpaper gallery", label: "Layout", description: "Showcase puts the chosen wallpaper on a large stage above one row; Strip is two compact rows; Wall fills three rows to browse many at once.", path: "iris.wallpaper.layout", kind: "choice", fallback: "showcase", choices: [{label:"Strip",value:"strip",glyph:"view_carousel"},{label:"Showcase",value:"showcase",glyph:"featured_video"},{label:"Wall",value:"wall",glyph:"view_module"}] },
        { target: "places", group: "Wallpaper gallery", label: "Gallery width", path: "iris.wallpaper.width", kind: "range", fallback:960,min:640,max:1400,step:40,unit:" px" },
        { target: "places", group: "Wallpaper gallery", label: "Preview size", path: "iris.wallpaper.thumbnailSize", kind: "range", fallback:228,min:160,max:320,step:8,unit:" px" },
        { target: "places", group: "Settings", label: "Corners", description: "Auto keeps the family's shape for Settings.", path: "iris.appearance.surfaces.settings.radius", kind: "range", fallback: 0, min: 0, max: 44, unit: " px", zeroLabel: "Auto" },
        { target: "places", group: "Settings", label: "Light", description: "Its own colour, the wallpaper's, or plain black.", path: "iris.appearance.surfaces.settings.light", kind: "choice", fallback: "inherit", choices: [{label:"Own",value:"inherit",glyph:"auto_awesome"},{label:"Wallpaper",value:"wallpaper",glyph:"wallpaper"},{label:"Off",value:"off",glyph:"light_off"}] },
        { target: "places", group: "Menus", label: "Corners", description: "Auto keeps the family's shape for menus.", path: "iris.appearance.surfaces.menus.radius", kind: "range", fallback: 0, min: 0, max: 44, unit: " px", zeroLabel: "Auto" },
        { target: "places", group: "Menus", label: "Light", description: "Its own colour, the wallpaper's, or plain black.", path: "iris.appearance.surfaces.menus.light", kind: "choice", fallback: "inherit", choices: [{label:"Own",value:"inherit",glyph:"auto_awesome"},{label:"Wallpaper",value:"wallpaper",glyph:"wallpaper"},{label:"Off",value:"off",glyph:"light_off"}] },
        { target: "transients", group: "Notifications", label: "Width", path: "iris.notifications.width", visibleWhen: "iris.modules.notificationPopup", kind: "range", fallback: 380, min: 340, max: 560, step: 10, unit: " px" },
        { target: "transients", group: "Feedback", label: "OSD width", path: "iris.osd.width", visibleWhen: "iris.modules.osd", kind: "range", fallback: 320, min: 260, max: 520, step: 10, unit: " px" },
        { target: "dock", group: "Look", label: "Screen edge", description: "Auto keeps the Dock on the edge opposite the Island. Choosing the Island's edge swaps them: the Island takes the Dock's place.", path: "iris.dock.position", kind: "choice", fallback: "auto", choices: root.dockEdgeChoices },
        { target: "dock", group: "Look", label: "Attach as a notch", path: "iris.dock.notch", kind: "switch", fallback:true },
        { target: "dock", group: "Look", label: "Material", description: "Follow iRiS, stay solid, glass over the blurred wallpaper, or real blur of the windows below (Niri 26.04+). Blur is still under construction: the Dock may look rough while it moves or opens a menu.", path: "iris.dock.material", kind: "choice", fallback: "inherit", choices: [{label:"iRiS",value:"inherit"},{label:"Solid",value:"solid"},{label:"Glass",value:"glass"},{label:"Blur (beta)",value:"blur"}] },
        { target: "dock", group: "Icons", label: "Icon size", path: "iris.dock.iconSize", kind: "range", fallback:40,min:28,max:64,unit:" px" },
        { target: "dock", group: "Icons", label: "Magnify on hover", path: "iris.dock.magnification", kind: "switch", fallback:false },
        { target: "dock", group: "Icons", label: "Magnification", visibleWhen: "iris.dock.magnification", description: "How large the icon under the pointer grows; its neighbours follow.", path: "iris.dock.magnifySize", kind: "range", fallback: 150, min: 110, max: 200, step: 5, unit: " %" },
        { target: "dock", group: "Icons", label: "Applications button", description: "Opens Spotlight from the start of the Dock.", path: "iris.dock.launcher", kind: "switch", fallback:true },
        { target: "desktop", group: "Widgets", label: "On the desktop", description: "Tap a widget to add it to this screen or take it away. Size, look and position are set on the widget itself: select it while arranging.", path: "background.widgets", kind: "widgets" },
        { target: "desktop", group: "Widgets", label: "Design", description: "iRiS draws each widget as one of its own faces at a fixed size class. Material keeps the shared Material family designs, with their own sizes and options. A widget can choose its own in its quick controls.", path: "iris.widgets.design", kind: "choice", fallback: "iris", choices: [{label:"iRiS",value:"iris",glyph:"auto_awesome"},{label:"Material",value:"material",glyph:"widgets"}] },
        { target: "desktop", group: "Widgets", label: "Widget corners", description: "Individual widget overrides take priority.", path: "iris.widgets.radius", kind: "range", fallback:22,min:0,max:40,unit:" px" },
        { target: "desktop", group: "Widgets", label: "Colour", description: "Wallpaper lifts its hues so they read on black; iRiS follows your system accent.", path: "iris.widgets.tint", kind: "choice", fallback: "wallpaper", choices: [{label:"Wallpaper",value:"wallpaper"},{label:"iRiS",value:"system"}] },
        { target: "desktop", group: "Widgets", label: "Material", description: "Glass frosts the wallpaper behind each widget; Transparent leaves it bare. Both darken only as much as the wallpaper under the widget needs for legible text. A widget can choose its own in its Look controls.", path: "iris.widgets.material", kind: "choice", fallback: "glass", choices: [{label:"Glass",value:"glass",glyph:"blur_on"},{label:"Transparent",value:"clear",glyph:"select"},{label:"Solid",value:"solid",glyph:"square"},{label:"Tinted",value:"tinted",glyph:"format_color_fill"}] },
        { target: "desktop", group: "Widgets", label: "Titles and figures", path: "iris.widgets.weight", kind: "choice", fallback: "regular", choices: [{label:"Light",value:"light"},{label:"Regular",value:"regular"},{label:"Bold",value:"bold"}] },
        { target: "desktop", group: "Widgets", label: "Surface opacity", path: "iris.widgets.opacity", description: "How much material a widget carries. Glass and Transparent never drop below what keeps their text readable.", kind: "range", fallback:100,min:20,max:100,step:5,unit:" %" },
        { target: "desktop", group: "Widgets", label: "Hairline on Transparent", description: "Transparent widgets float bare on the wallpaper. Turn this on to keep a faint outline around them; while arranging, the outline always shows.", path: "iris.widgets.rim", kind: "switch", fallback: false }
    ]

    readonly property var bubbleRows: {
        const rows = []
        for (const piece of IrisPieces.slots)
            rows.push({ section: "bubbles", group: "Placement", label: piece.label, description: piece.description,
                piece: piece.id,
                path: IrisPieces.configPath(piece.id) + ".place", kind: "zone", fallback: "island",
                choices: IrisPieces.zoneChoices(true) })
        for (const piece of IrisPieces.extras) {
            const path = IrisPieces.configPath(piece.id)
            rows.push({ section: "bubbles", group: "Extra bubbles", label: piece.label, description: piece.description,
                piece: piece.id,
                path: path + ".enable", kind: "switch", fallback: false })
            rows.push({ section: "bubbles", group: "Extra bubbles", label: piece.label + " bubble rests",
                piece: piece.id,
                path: path + ".place", visibleWhen: path + ".enable", kind: "zone",
                fallback: IrisPieces.defaultPlace, choices: IrisPieces.zoneChoices(false) })
            if (piece.id === "workspaces") {
                rows.push({ section: "bubbles", group: "Workspaces", label: "Tap opens", description: "Open Niri's Overview, or grow a workspace switcher from this bubble.", piece: piece.id,
                    path: path + ".opens", visibleWhen: path + ".enable", kind: "choice", fallback: "card",
                    choices: [{label:"Overview",value:"overview",glyph:"space_dashboard"},{label:"Workspace card",value:"card",glyph:"view_carousel"}] })
            }
        }
        return rows
    }

    readonly property var behaviour: [
        { section: "appearance", group: "Look", label: "Base look", description: "The starting shape and contrast language. Studio tweaks stay on top of it.", path: "iris.appearance.preset", kind: "choice", fallback: "iris", choices: [{label:"iRiS",value:"iris"},{label:"Soft",value:"soft"},{label:"Round",value:"round"},{label:"Crisp",value:"crisp"},{label:"Angular",value:"angular"},{label:"Contrast",value:"contrast"}] },
        { section: "bar", group: "Layout", label: "Composition", description: "Cluster splits media and controls into bubbles beside the clock.", path: "iris.bar.composition", kind: "choice", fallback: "cluster", choices: [{label:"Unified",value:"unified",glyph:"crop_7_5"},{label:"Cluster",value:"cluster",glyph:"bubble_chart"}] },
        { section: "bar", group: "Size", label: "Reserve space for windows", path: "iris.bar.reserveSpace", kind: "switch", fallback:true },
        { section: "bar", group: "Interaction", label: "System events", description: "Charger, Bluetooth devices, Do Not Disturb, Caps Lock and finished timers or recordings appear in the Island for a moment.", path: "iris.bar.events", kind: "switch", fallback: true },
        { section: "bar", group: "Interaction", label: "Caps Lock badge", description: "A small pill drops out of the Island when Caps Lock turns on or off.", path: "keyboardIndicators.popup.caps", visibleWhen: "iris.bar.events", kind: "switch", fallback: true },
        { section: "bar", group: "Interaction", label: "Expand on hover", description: "The pointer has to rest on the Island; passing over it does nothing. A full-width Island always opens on a click instead.", path: "iris.bar.hoverExpand", kind: "switch", fallback:true },
        { section: "bar", group: "Interaction", label: "Hover delay", path: "iris.bar.hoverDelay", kind: "range", fallback:300,min:120,max:800,step:20,unit:" ms" },
        { section: "bar", group: "Interaction", label: "Scroll on the Island", description: "On the resting Island: Shift swaps volume and brightness; Ctrl adjusts the microphone. On the open Island scrolling never closes it: over the navigation row, or sideways anywhere, it moves between pages.", path: "iris.bar.scrollAction", kind: "choice", fallback: "volume", choices: [{label:"Volume",value:"volume"},{label:"Brightness",value:"brightness"},{label:"Off",value:"none"}] },
        { section: "bar", group: "Interaction", label: "Scroll on bubbles", description: "Also adjust over the media, controls and tray bubbles. Sound and Microphone bubbles always adjust their level.", path: "iris.bar.scrollBubbles", kind: "switch", fallback: true },
        { section: "bar", group: "Resting Island", label: "Trailing bubble", description: "Cluster only. Sound and Microphone show their level: scroll to adjust, click to mute.", path: "iris.bar.trailing", kind: "choice", fallback: "controls", choices: [{label:"Controls",value:"controls"},{label:"Notifications",value:"notifications"},{label:"Weather",value:"weather"},{label:"Sound",value:"sound"},{label:"Microphone",value:"mic"},{label:"None",value:"none"}] },
        { section: "bar", group: "Resting Island", label: "Bubbles in the Island", description: "Small faces the Island carries itself, in the order you switch them on. Each one opens its card, and levels adjust on scroll.", path: "iris.bar.pieces", kind: "pieces", fallback: [], choices: IrisPieces.extras.map(piece => ({ label: piece.label, value: piece.id })) },
        { section: "bar", group: "Bar", visibleWhen: "iris.bar.layout=full", label: "Start", description: "What rests at the start of the full-width Island, in the order you switch it on. The Island itself is the live part: the time, or whatever is happening.", path: "iris.bar.fullStart", kind: "pieces", fallback: ["workspaces", "window"], choices: root.barZoneChoices },
        { section: "bar", group: "Bar", visibleWhen: "iris.bar.layout=full", label: "Centre", description: "Kept in the middle of the edge while there is room.", path: "iris.bar.fullCenter", kind: "pieces", fallback: ["island"], choices: root.barZoneChoices },
        { section: "bar", group: "Bar", visibleWhen: "iris.bar.layout=full", label: "End", description: "What rests at the far end. A piece that also floats on its own is left out here: one piece, one place.", path: "iris.bar.fullEnd", kind: "pieces", fallback: ["tray", "notifications", "sound", "controls"], choices: root.barZoneChoices },
        { section: "player", group: "Bubble", label: "Media bubble opens", description: "A card that floats out of the bubble, or the Island's player page. Cluster composition only.", path: "iris.player.bubbleOpens", kind: "choice", fallback: "card", choices: [{label:"Card",value:"card",glyph:"web_asset"},{label:"Island",value:"island",glyph:"pill"}] },
        { section: "player", group: "Bubble", label: "Keep the card open", description: "The card stays beside the Island while a player is active.", path: "iris.player.cardPinned", kind: "switch", fallback: false },
    ].concat(root.bubbleRows, [
        { section: "bubbles", group: "Behaviour", label: "Tapping a bubble", description: "Grow it into a card of its own, or open the Island page or panel it stands for (level bubbles then mute).", path: "iris.bubbles.opens", kind: "choice", fallback: "card", choices: [{label:"Opens its card",value:"card",glyph:"web_asset"},{label:"Opens the Island",value:"island",glyph:"pill"}] },
        { section: "bubbles", group: "Floating", label: "Make room for them", description: "An edge carrying bubbles takes its space from the desktop, like the Island's edge does, so windows are never covered by them.", path: "iris.bubbles.reserve", visibleWhen: "iris.bubbles.attach", kind: "switch", fallback: true },
        { section: "bubbles", group: "Floating", label: "Space from the screen edges", description: "How far floating bubbles rest from the edges when they are not on the frame.", path: "iris.bubbles.edgeGap", visibleWhen: "!iris.bubbles.attach", kind: "range", fallback: 20, min: 0, max: 64, unit: " px" },
        { section: "bubbles", group: "Floating", label: "Snap to corners and edges", description: "Dropped near one, a bubble settles there; off, it stays where you let go.", path: "iris.bubbles.snap", kind: "switch", fallback: true },
        { section: "dock", group: "Visibility", label: "Show dock", path: "iris.dock.enable", kind: "switch", fallback:true },
        { section: "dock", group: "Visibility", label: "Automatically hide", description: "Rest the pointer at the screen edge to reveal it.", path: "iris.dock.autoHide", kind: "switch", fallback:true },
        { section: "dock", group: "Visibility", label: "Reserve space for windows", description: "Keep tiled windows clear of the visible Dock. Turn this off to let the Dock sit over them.", path: "iris.dock.reserveSpace", visibleWhen: "!iris.dock.autoHide", kind: "switch", fallback:true },
        { section: "dock", group: "Visibility", label: "Stay visible on empty workspaces", path: "iris.dock.revealOnEmpty", kind: "switch", fallback:true },
        { section: "dock", group: "Icons", label: "Notification badges", path: "iris.dock.badges", kind: "switch", fallback:true },
        { section: "appearance", group: "Motion", label: "Reduce motion", description: "Surfaces appear in place. Shapes and joins stay the same.", path: "iris.appearance.motion", invert: true, kind: "switch", fallback: true },
        { section: "desktop", group: "Widgets", label: "Desktop widgets", description: "Turning this off also unloads their data providers.", path: "iris.modules.desktopWidgets", kind: "switch", fallback:true },
        { section: "desktop", group: "Overview backdrop", label: "Wallpaper behind the overview", description: "Shown around workspaces when Niri's overview is open.", path: "background.backdrop.enable", kind: "switch", fallback:true },
        { section: "desktop", group: "Overview backdrop", label: "Same wallpaper as the desktop", description: "Off keeps the overview's own wallpaper; choose it in the gallery with Overview as the target.", path: "background.backdrop.useMainWallpaper", kind: "switch", fallback: true },
        { section: "desktop", group: "Overview backdrop", label: "Animate in the overview", description: "A live wallpaper moves behind the workspaces, only while the overview is open.", path: "background.backdrop.enableAnimation", kind: "switch", fallback: false },
        { section: "desktop", group: "Overview backdrop", label: "Blur", path: "background.backdrop.blurRadius", kind: "range", fallback:40,min:0,max:100,unit:" px" },
        { section: "desktop", group: "Overview backdrop", label: "Dim", path: "background.backdrop.dim", kind: "range", fallback:40,min:0,max:100,unit:" %" },
        { section: "desktop", group: "Overview backdrop", label: "Vignette", path: "background.backdrop.vignetteEnabled", kind: "switch", fallback:false },
        { section: "appearance", group: "Previews", label: "Animated previews", description: "The live scenes and miniatures in Settings and Studio. Off, none of them is built, which saves memory and a little work while you browse.", path: "iris.appearance.previews", kind: "switch", fallback: true },
        { section: "surfaces", group: "Spotlight", label: "Spotlight", path: "iris.modules.palette", kind: "switch", fallback:true },
        { section: "surfaces", group: "Spotlight", label: "Maximum results", path: "iris.palette.maxResults", kind: "range", fallback:8,min:3,max:14 },
        { section: "surfaces", group: "Spotlight", label: "Search mode shortcuts", description: "Clipboard, calculator, actions and more under the suggestions.", path: "iris.palette.showHints", kind: "switch", fallback:true },
        { section: "surfaces", group: "Control Center", label: "Control Center", path: "iris.modules.controlCenter", kind: "switch", fallback:true },
        { section: "surfaces", group: "Tray", label: "App names", path: "iris.tray.labels", kind: "switch", fallback:true },
        { section: "surfaces", group: "Tray", label: "Hide passive apps", path: "iris.tray.hidePassive", kind: "switch", fallback:false },
        { section: "surfaces", group: "Tray", label: "Columns", path: "iris.tray.columns", kind: "range", fallback:4,min:2,max:6 },
        { section: "desktop", group: "Wallpaper gallery", label: "Preview on the desktop", description: "The highlighted wallpaper shows behind the gallery; closing without applying restores yours.", path: "iris.wallpaper.livePreview", kind: "switch", fallback: true },
        { section: "desktop", group: "Wallpaper gallery", label: "Play previews", description: "Live wallpapers play a muted preview while chosen or hovered in the gallery. Only one plays at a time.", path: "iris.wallpaper.motion", kind: "switch", fallback: true },
        { section: "desktop", group: "Live wallpapers", label: "Animate on the desktop", description: "Video and GIF wallpapers move. Off keeps a sharp still frame and no decoder.", path: "background.enableAnimation", kind: "switch", fallback: true },
        { section: "desktop", group: "Live wallpapers", label: "Pause", description: "A hidden wallpaper stops decoding and keeps its frame. When covered pauses once tiled windows fill the screen; Never keeps it moving under everything.", path: "background.videoPause", kind: "choice", fallback: "covered", choices: [{label:"Never",value:"never",glyph:"play_arrow"},{label:"Behind fullscreen",value:"fullscreen",glyph:"fullscreen"},{label:"When covered",value:"covered",glyph:"view_column"}] },
        { section: "desktop", group: "Live wallpapers", label: "Pause on battery", path: "background.pauseAnimationOnBattery", kind: "switch", fallback: true },
        { section: "desktop", group: "Live wallpapers", label: "Animate on the lock screen", description: "Plays while the lock screen's blur is off.", path: "lock.enableAnimation", kind: "switch", fallback: false },
        { section: "surfaces", group: "Feedback", label: "Notifications", path: "iris.modules.notificationPopup", kind: "switch", fallback:true },
        { section: "surfaces", group: "Feedback", label: "Banner duration", description: "How long a notification stays when the app does not choose. Hovering keeps it.", path: "iris.notifications.duration", kind: "range", fallback:4000,min:2000,max:12000,step:500,unit:" ms" },
        { section: "surfaces", group: "Feedback", label: "Volume and brightness feedback", path: "iris.modules.osd", kind: "switch", fallback:true },
        { section: "surfaces", group: "Windows", label: "Confirm before closing windows", description: "Asks before the close-window shortcut closes an app.", path: "closeConfirm.enabled", kind: "switch", fallback:false }
    ].concat(...["left", "right"].map(side => [
        { section: "sidebars", group: side === "left" ? "Focus · left" : "Today · right", label: "Enable panel", path: "iris.sidebars." + side + ".enable", kind: "switch", fallback:true },
        { section: "sidebars", group: side === "left" ? "Focus · left" : "Today · right", label: "Width", path: "iris.sidebars." + side + ".width", kind: "range", fallback:380,min:300,max:600,step:10,unit:" px" },
        { section: "sidebars", group: side === "left" ? "Focus · left" : "Today · right", label: "Maximum height", description: "Panels hug their sections and grow up to this.", path: "iris.sidebars." + side + ".height", kind: "range", fallback:88,min:45,max:100,unit:" %" },
        { section: "sidebars", group: side === "left" ? "Focus · left" : "Today · right", label: "Alignment", path: "iris.sidebars." + side + ".alignment", kind: "choice", fallback:"center", choices:[{label:"Top",value:"top"},{label:"Center",value:"center"},{label:"Bottom",value:"bottom"}] },
        { section: "sidebars", group: side === "left" ? "Focus · left" : "Today · right", label: "Attach to the screen edge", description: "Melts the panel into its edge, like a notch.", path: "iris.sidebars." + side + ".notch", kind: "switch", fallback:false },
        { section: "sidebars", group: side === "left" ? "Focus · left" : "Today · right", label: "Reveal on hover", description: side === "left" ? "Rest the pointer at the left edge to peek; click inside to keep it." : "Rest the pointer at the right edge to peek; click inside to keep it.", path: "iris.sidebars." + side + ".hoverReveal", kind: "switch", fallback:false },
        { section: "sidebars", group: side === "left" ? "Focus · left" : "Today · right", label: "Keep open", description: "Stay visible while working in other windows.", path: "iris.sidebars." + side + ".pinned", kind: "switch", fallback:false },
        { section: "sidebars", group: side === "left" ? "Focus · left" : "Today · right", label: "Reserve space for windows", description: "Keep tiled windows clear while this panel is kept open. Turn this off to let the panel overlay them.", path: "iris.sidebars." + side + ".reserveSpace", visibleWhen: "iris.sidebars." + side + ".pinned", kind: "switch", fallback:true }
    ])))

    readonly property var dockEdgeChoices: [{ label: "Auto", value: "auto", glyph: "auto_mode" }].concat([
        { label: "Bottom", value: "bottom", glyph: "vertical_align_bottom" }, { label: "Top", value: "top", glyph: "vertical_align_top" },
        { label: "Left", value: "left", glyph: "align_horizontal_left" }, { label: "Right", value: "right", glyph: "align_horizontal_right" }
    ])
    readonly property var barZoneChoices: [
        { label: "Island", value: "island" }, { label: "Workspaces", value: "workspaces" },
        { label: "Current window", value: "window" }, { label: "Time", value: "time" }
    ].concat(IrisPieces.extras.filter(piece => piece.id !== "workspaces").map(piece => ({ label: piece.label, value: piece.id })))
    readonly property var sectionOrder: ["bar", "player", "bubbles", "dock", "appearance", "desktop", "sidebars", "surfaces", "system"]
    function sectionOf(spec: var): string {
        const path = String(spec.path ?? "")
        switch (spec.target) {
        case "island": return "bar"
        case "pieces": return "bubbles"
        case "bodies": return path.startsWith("iris.player.") ? "player" : "surfaces"
        case "places": return path.startsWith("iris.wallpaper.") || path.includes(".gallery.") ? "desktop" : "surfaces"
        case "transients": return "surfaces"
        case "dock": return "dock"
        case "desktop": return "desktop"
        default: return "appearance"
        }
    }
    readonly property var settings: {
        const known = new Set(root.behaviour.map(spec => spec.path))
        const look = []
        for (const spec of root.studio) {
            if (known.has(spec.path)) continue
            known.add(spec.path)
            look.push(Object.assign({ section: root.sectionOf(spec) }, spec))
        }
        const out = []
        for (const section of root.sectionOrder) {
            for (const spec of root.behaviour) if (spec.section === section) out.push(spec)
            for (const spec of look) if (spec.section === section) out.push(spec)
        }
        return out
    }
}
