#!/usr/bin/env python3
"""
Generate Neovim colorscheme from Material You colors (material_colors.scss).
Outputs ~/.config/nvim/colors/iNiR.vim

The colorscheme is loaded via:
  colorscheme iNiR          (init.vim)
  vim.cmd("colorscheme iNiR") (init.lua)

Running Neovim instances are reloaded via SIGUSR1, which triggers:
  autocmd Signal SIGUSR1 colorscheme iNiR

Part of iNiR wallpaper theming pipeline.
Called from applycolor.sh.
"""

import os
import re
import subprocess
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# Color helpers
# ---------------------------------------------------------------------------


def parse_scss_colors(scss_path: str) -> dict[str, str]:
    """Parse material_colors.scss and extract hex color variables."""
    colors: dict[str, str] = {}
    try:
        with open(scss_path, "r") as f:
            for line in f:
                match = re.match(r"\$(\w+):\s*(#[A-Fa-f0-9]{6});", line.strip())
                if match:
                    name, value = match.groups()
                    colors[name] = value.lower()
    except FileNotFoundError:
        print(f"Error: {scss_path} not found", file=sys.stderr)
        sys.exit(1)
    return colors


def hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    h = hex_color.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def blend(c1: str, c2: str, factor: float = 0.5) -> str:
    """Blend two hex colors. factor=0 → c1, factor=1 → c2."""
    r1, g1, b1 = hex_to_rgb(c1)
    r2, g2, b2 = hex_to_rgb(c2)
    r = int(r1 + (r2 - r1) * factor)
    g = int(g1 + (g2 - g1) * factor)
    b = int(b1 + (b2 - b1) * factor)
    return f"#{r:02x}{g:02x}{b:02x}"


# ---------------------------------------------------------------------------
# Template - Full theme with 30% primary blend on syntax colors
# Uses guibg=NONE for transparency so terminal background shows through
# ---------------------------------------------------------------------------

VIM_TEMPLATE = """\
" Auto-generated by iNiR wallpaper theming system
" Do not edit manually - changes will be overwritten on next wallpaper change

set background={background_mode}
hi clear
if exists('syntax_on')
  syntax reset
endif
let g:colors_name = 'iNiR'

" Terminal transparency - let the terminal background show through
set winblend=30
set pumblend=30

" ── Core UI (translucent backgrounds) ────────────────────────────────────────
hi Normal       guifg={on_surface}        guibg=NONE gui=NONE
hi NormalFloat  guifg={on_surface}        guibg=NONE gui=NONE
hi NormalNC     guifg={on_surface_variant} guibg=NONE gui=NONE

" ── Cursor & Selection ──────────────────────────────────────────────────────
hi Cursor       guifg={surface}           guibg={primary}         gui=NONE
hi CursorLine   guibg=NONE                                              gui=NONE
hi CursorColumn guibg=NONE                                              gui=NONE
hi Visual       guibg=NONE                                              gui=NONE
hi VisualNOS    guibg=NONE                                              gui=underline

" ── Line numbers & sign column ─────────────────────────────────────────────
hi LineNr       guifg={outline}           guibg=NONE              gui=NONE
hi CursorLineNr guifg={primary}           guibg=NONE              gui=bold
hi SignColumn   guibg=NONE                                         gui=NONE
hi FoldColumn   guifg={outline}           guibg=NONE              gui=NONE
hi Folded       guifg={on_surface_variant} guibg=NONE             gui=italic

" ── Status & Tab line ───────────────────────────────────────────────────────
hi StatusLine   guifg={on_surface}        guibg=NONE gui=NONE
hi StatusLineNC guifg={outline}           guibg=NONE gui=NONE
hi TabLine      guifg={outline}           guibg=NONE gui=NONE
hi TabLineFill  guibg=NONE                                          gui=NONE
hi TabLineSel   guifg={on_primary}        guibg={primary}         gui=bold

" ── Pop-up menu ─────────────────────────────────────────────────────────────
hi Pmenu        guifg={on_surface}        guibg=NONE gui=NONE
hi PmenuSel     guifg={on_primary_container} guibg={primary_container} gui=NONE
hi PmenuSbar    guibg=NONE                                             gui=NONE
hi PmenuThumb   guibg={outline}                                    gui=NONE

" ── Search ─────────────────────────────────────────────────────────────────
hi Search       guifg={surface}           guibg={tertiary}        gui=NONE
hi IncSearch    guifg={surface}           guibg={primary}         gui=bold
hi CurSearch    guifg={surface}           guibg={primary}         gui=bold

" ── Messages & prompts ──────────────────────────────────────────────────────
hi ModeMsg      guifg={primary}                                    gui=bold
hi MoreMsg      guifg={secondary}                                  gui=bold
hi Question     guifg={tertiary}                                   gui=bold
hi WarningMsg   guifg={term3}                                      gui=bold
hi ErrorMsg     guifg={error}             guibg=NONE              gui=bold

" ── Diff ────────────────────────────────────────────────────────────────────
hi DiffAdd      guifg={term2}             guibg=NONE              gui=NONE
hi DiffChange   guifg={term3}             guibg=NONE              gui=NONE
hi DiffDelete   guifg={term1}             guibg=NONE              gui=bold
hi DiffText     guifg={term11}            guibg=NONE              gui=bold

" ── Diagnostics (LSP) ─────────────────────────────────────────────────────
hi DiagnosticError         guifg={error}                          gui=NONE
hi DiagnosticWarn          guifg={term3}                          gui=NONE
hi DiagnosticInfo          guifg={primary}                        gui=NONE
hi DiagnosticHint          guifg={secondary}                      gui=NONE
hi DiagnosticUnderlineError guisp={error}                         gui=undercurl
hi DiagnosticUnderlineWarn  guisp={term3}                         gui=undercurl
hi DiagnosticUnderlineInfo  guisp={primary}                       gui=undercurl
hi DiagnosticUnderlineHint  guisp={secondary}                     gui=undercurl

" ── Borders & Separators ───────────────────────────────────────────────────
hi VertSplit    guifg={outline_variant}   guibg=NONE              gui=NONE
hi WinSeparator guifg={outline_variant}   guibg=NONE              gui=NONE

" ── Spell ─────────────────────────────────────────────────────────────────
hi SpellBad     guisp={error}                                      gui=undercurl
hi SpellCap     guisp={term4}                                      gui=undercurl
hi SpellLocal   guisp={term6}                                      gui=undercurl
hi SpellRare    guisp={secondary}                                  gui=undercurl

" ── Misc ───────────────────────────────────────────────────────────────────
hi NonText      guifg={outline}                                    gui=NONE
hi SpecialKey   guifg={outline}                                    gui=NONE
hi Conceal      guifg={outline}           guibg=NONE              gui=NONE
hi Directory    guifg={primary}                                    gui=bold
hi Title        guifg={primary}                                    gui=bold
hi MatchParen   guifg={surface}           guibg={tertiary}        gui=bold
hi ColorColumn  guibg=NONE                                              gui=NONE
hi QuickFixLine guibg=NONE                                              gui=NONE
hi WildMenu     guifg={on_primary}        guibg={primary}         gui=bold

" ── Default Syntax (blended 30% with primary) ──────────────────────────────
hi Comment      guifg={syntax_comment}                            gui=italic
hi Constant     guifg={syntax_constant}                           gui=NONE
hi String       guifg={syntax_string}                             gui=NONE
hi Character    guifg={syntax_character}                          gui=NONE
hi Number       guifg={syntax_number}                             gui=NONE
hi Boolean      guifg={syntax_boolean}                            gui=bold
hi Float        guifg={syntax_float}                             gui=NONE
hi Identifier   guifg={syntax_identifier}                         gui=NONE
hi Function     guifg={syntax_function}                           gui=NONE
hi Statement    guifg={syntax_statement}                         gui=bold
hi Conditional  guifg={syntax_conditional}                       gui=bold
hi Repeat       guifg={syntax_repeat}                            gui=bold
hi Label        guifg={syntax_label}                             gui=bold
hi Operator     guifg={syntax_operator}                           gui=NONE
hi Keyword      guifg={syntax_keyword}                           gui=bold
hi Exception    guifg={syntax_exception}                          gui=bold
hi PreProc      guifg={syntax_preproc}                           gui=NONE
hi Include      guifg={syntax_include}                           gui=NONE
hi Define       guifg={syntax_define}                           gui=NONE
hi Macro        guifg={syntax_macro}                             gui=NONE
hi PreCondit    guifg={syntax_precondit}                         gui=NONE
hi Type         guifg={syntax_type}                             gui=NONE
hi StorageClass guifg={syntax_storageclass}                      gui=bold
hi Structure    guifg={syntax_structure}                         gui=bold
hi Typedef      guifg={syntax_typedef}                           gui=bold
hi Special      guifg={syntax_special}                           gui=NONE
hi SpecialChar  guifg={syntax_specialchar}                        gui=NONE
hi Tag          guifg={syntax_tag}                             gui=NONE
hi Delimiter    guifg={syntax_delimiter}                         gui=NONE
hi SpecialComment guifg={syntax_specialcomment}                  gui=italic,bold
hi Debug        guifg={syntax_debug}                             gui=NONE
hi Underlined   guifg={syntax_underlined}                        gui=underline
hi Ignore       guifg={syntax_ignore}                           gui=NONE
hi Error        guifg={error}             guibg=NONE            gui=bold,underline
hi Todo         guifg={syntax_todo}           guibg={tertiary}        gui=bold

" ── Treesitter (link to base syntax groups) ────────────────────────────────
hi! link @comment            Comment
hi! link @comment.documentation Comment
hi! link @variable           Identifier
hi! link @variable.builtin   Special
hi! link @constant           Constant
hi! link @constant.builtin   Boolean
hi! link @constant.macro     Define
hi! link @string             String
hi! link @string.escape      SpecialChar
hi! link @string.special     SpecialChar
hi! link @character          Character
hi! link @number             Number
hi! link @float              Float
hi! link @boolean            Boolean
hi! link @function           Function
hi! link @function.builtin   Special
hi! link @function.macro     Macro
hi! link @method             Function
hi! link @constructor        Function
hi! link @parameter          Identifier
hi! link @keyword            Keyword
hi! link @keyword.function   Keyword
hi! link @keyword.operator   Operator
hi! link @keyword.return     Statement
hi! link @conditional        Conditional
hi! link @repeat             Repeat
hi! link @exception          Exception
hi! link @type               Type
hi! link @type.builtin       Type
hi! link @type.definition    Typedef
hi! link @storageclass       StorageClass
hi! link @namespace          PreProc
hi! link @include            Include
hi! link @operator           Operator
hi! link @punctuation.bracket Delimiter
hi! link @punctuation.delimiter Delimiter
hi! link @punctuation.special Special
hi! link @label              Label
hi! link @tag                Tag
hi! link @tag.attribute      Identifier
hi! link @tag.delimiter      Delimiter
hi! link @text.title         Title
hi! link @text.uri           Underlined
hi! link @text.emphasis      Italic
hi! link @text.strong        Bold
hi! link @text.literal       String
hi! link @text.reference     Constant

" ── LSP semantic tokens ───────────────────────────────────────────────────
hi! link @lsp.type.class     Type
hi! link @lsp.type.enum      Type
hi! link @lsp.type.function  Function
hi! link @lsp.type.interface Type
hi! link @lsp.type.keyword   Keyword
hi! link @lsp.type.macro     Macro
hi! link @lsp.type.method    Function
hi! link @lsp.type.namespace PreProc
hi! link @lsp.type.parameter Identifier
hi! link @lsp.type.property  Identifier
hi! link @lsp.type.string    String
hi! link @lsp.type.type      Type
hi! link @lsp.type.variable  Identifier
hi! link @lsp.mod.deprecated DiagnosticUnderlineWarn
hi! link @lsp.mod.readonly   Constant

" ── Git signs (gitsigns.nvim) ────────────────────────────────────────────
hi GitSignsAdd    guifg={term2}  guibg=NONE  gui=NONE
hi GitSignsChange guifg={term3}  guibg=NONE  gui=NONE
hi GitSignsDelete guifg={term1}  guibg=NONE  gui=NONE

" ── Telescope (telescope.nvim) ────────────────────────────────────────────
hi TelescopeBorder         guifg={outline_variant}  guibg=NONE  gui=NONE
hi TelescopeNormal         guifg={on_surface}        guibg=NONE
hi TelescopePromptNormal   guifg={on_surface}        guibg=NONE
hi TelescopeResultsNormal  guifg={on_surface}        guibg=NONE
hi TelescopePreviewNormal  guifg={on_surface}        guibg=NONE
hi TelescopeSelection      guifg={on_primary_container} guibg={primary_container}
hi TelescopeMatching       guifg={primary}                       gui=bold
hi TelescopePromptPrefix   guifg={primary}                       gui=bold

" ── Which-key (which-key.nvim) ────────────────────────────────────────────
hi WhichKey          guifg={primary}                             gui=bold
hi WhichKeyGroup     guifg={secondary}                           gui=bold
hi WhichKeyDesc      guifg={on_surface}                          gui=NONE
hi WhichKeySeparator guifg={outline}                             gui=NONE
hi WhichKeyFloat     guibg=NONE                                   gui=NONE

" ── nvim-cmp ───────────────────────────────────────────────────────────────
hi CmpItemAbbrMatch       guifg={primary}                        gui=bold
hi CmpItemAbbrMatchFuzzy  guifg={tertiary}                       gui=bold
hi CmpItemKindText        guifg={on_surface_variant}             gui=NONE
hi CmpItemKindFunction    guifg={term4}                          gui=NONE
hi CmpItemKindMethod      guifg={term4}                          gui=NONE
hi CmpItemKindVariable    guifg={on_surface}                     gui=NONE
hi CmpItemKindKeyword     guifg={term5}                          gui=NONE
hi CmpItemKindSnippet     guifg={tertiary}                       gui=NONE
hi CmpItemKindModule      guifg={term6}                          gui=NONE
hi CmpItemKindClass       guifg={term3}                          gui=NONE
hi CmpItemKindInterface   guifg={term3}                          gui=NONE
hi CmpItemKindField       guifg={on_surface}                     gui=NONE
hi CmpItemKindProperty    guifg={on_surface}                     gui=NONE
hi CmpItemKindEnum        guifg={term3}                          gui=NONE
hi CmpItemKindUnit        guifg={term5}                          gui=NONE
hi CmpItemKindValue       guifg={term5}                          gui=NONE
hi CmpItemKindConstructor guifg={term4}                          gui=NONE
hi CmpItemKindOperator    guifg={on_surface_variant}             gui=NONE

" ── Italic / Bold helpers ─────────────────────────────────────────────────
hi Italic  gui=italic
hi Bold    gui=bold

" ── Terminal colors (for :terminal) ────────────────────────────────────────
let g:terminal_color_0  = '{term0}'
let g:terminal_color_1  = '{term1}'
let g:terminal_color_2  = '{term2}'
let g:terminal_color_3  = '{term3}'
let g:terminal_color_4  = '{term4}'
let g:terminal_color_5  = '{term5}'
let g:terminal_color_6  = '{term6}'
let g:terminal_color_7  = '{term7}'
let g:terminal_color_8  = '{term8}'
let g:terminal_color_9  = '{term9}'
let g:terminal_color_10 = '{term10}'
let g:terminal_color_11 = '{term11}'
let g:terminal_color_12 = '{term12}'
let g:terminal_color_13 = '{term13}'
let g:terminal_color_14 = '{term14}'
let g:terminal_color_15 = '{term15}'
"""


# ---------------------------------------------------------------------------
# Auto-integration helpers
# ---------------------------------------------------------------------------

INIT_VIM_SNIPPET = """\

" iNiR wallpaper theming - Neovim colorscheme
colorscheme iNiR
autocmd Signal SIGUSR1 colorscheme iNiR
"""

INIT_LUA_SNIPPET = """\

-- iNiR wallpaper theming - Neovim colorscheme
vim.cmd("colorscheme iNiR")
vim.api.nvim_create_autocmd("Signal", {
    pattern = "SIGUSR1",
    command = "colorscheme iNiR",
})
"""

COLORSCHEME_PATTERN_VIM = r"colorscheme\s+iNiR"
COLORSCHEME_PATTERN_LUA = r'colorscheme\s*["\']?iNiR'


def ensure_nvim_integration(nvim_config_dir: str) -> str:
    """
    Inject colorscheme + autocmd into init.vim or init.lua if not already present.
    Returns a human-readable status message.
    """
    config_dir = Path(nvim_config_dir)

    for fname, snippet, pattern in [
        ("init.vim", INIT_VIM_SNIPPET, COLORSCHEME_PATTERN_VIM),
        ("init.lua", INIT_LUA_SNIPPET, COLORSCHEME_PATTERN_LUA),
    ]:
        cfg = config_dir / fname
        if cfg.exists():
            content = cfg.read_text()
            if re.search(pattern, content):
                return f"already integrated ({fname})"
            cfg.write_text(content.rstrip("\n") + "\n" + snippet)
            return f"integrated into {fname}"

    return "no init.vim or init.lua found (skipped auto-integration)"


def reload_neovim() -> None:
    """Send SIGUSR1 to all running nvim processes."""
    try:
        result = subprocess.run(
            ["pkill", "--signal", "SIGUSR1", "-x", "nvim"],
            capture_output=True,
            timeout=3,
        )
        if result.returncode == 0:
            print("[neovim] Sent SIGUSR1 to running nvim instances")
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------


def generate_neovim_theme(scss_path: str, output_dir: str | None = None) -> str:
    """Parse SCSS, build colorscheme, write to disk. Returns output path."""
    colors = parse_scss_colors(scss_path)

    if not colors:
        print("Error: No colors parsed from SCSS", file=sys.stderr)
        sys.exit(1)

    # Detect dark/light mode
    is_dark = colors.get("darkmode", "True").lower() != "false"
    background_mode = "dark" if is_dark else "light"

    # Material You tokens
    primary = colors.get("primary", "#7aa2f7")
    on_primary = colors.get("onPrimary", "#1a1b26")
    primary_container = colors.get("primaryContainer", "#004c6b")
    on_primary_container = colors.get("onPrimaryContainer", "#c6e7ff")
    secondary = colors.get("secondary", "#bb9af7")
    tertiary = colors.get("tertiary", "#9ece6a")
    surface = colors.get("surface", "#0f1417")
    surface_dim = colors.get("surfaceDim", "#0d1114")
    surface_container = colors.get("surfaceContainer", "#1c2024")
    surface_container_low = colors.get("surfaceContainerLow", "#181c1f")
    surface_container_high = colors.get("surfaceContainerHigh", "#262b2e")
    on_surface = colors.get("onSurface", "#dfe3e7")
    on_surface_variant = colors.get("onSurfaceVariant", "#c1c7ce")
    outline = colors.get("outline", "#8b9298")
    outline_variant = colors.get("outlineVariant", "#41484d")
    error = colors.get("error", "#ffb4ab")

    # ANSI terminal colors
    term = {i: colors.get(f"term{i}", "#888888") for i in range(16)}

    # Default syntax colors (base vim colors blended 30% with primary)
    # Using a warm palette that works well with most languages
    syntax_comment = blend(outline, primary, 0.30)
    syntax_constant = blend(term[5], primary, 0.30)  # magenta-ish
    syntax_string = blend(term[2], primary, 0.30)  # green-ish
    syntax_character = blend(term[2], primary, 0.30)
    syntax_number = blend(term[5], primary, 0.30)
    syntax_boolean = blend(term[5], primary, 0.30)
    syntax_float = blend(term[5], primary, 0.30)
    syntax_identifier = blend(on_surface, primary, 0.30)
    syntax_function = blend(term[4], primary, 0.30)  # blue-ish
    syntax_statement = blend(term[1], primary, 0.30)  # red-ish
    syntax_conditional = blend(term[1], primary, 0.30)
    syntax_repeat = blend(term[1], primary, 0.30)
    syntax_label = blend(term[1], primary, 0.30)
    syntax_operator = blend(on_surface_variant, primary, 0.30)
    syntax_keyword = blend(term[5], primary, 0.30)  # magenta-ish
    syntax_exception = blend(error, primary, 0.30)
    syntax_preproc = blend(term[6], primary, 0.30)  # cyan-ish
    syntax_include = blend(term[6], primary, 0.30)
    syntax_define = blend(term[6], primary, 0.30)
    syntax_macro = blend(term[6], primary, 0.30)
    syntax_precondit = blend(term[6], primary, 0.30)
    syntax_type = blend(term[3], primary, 0.30)  # yellow-ish
    syntax_storageclass = blend(term[3], primary, 0.30)
    syntax_structure = blend(term[3], primary, 0.30)
    syntax_typedef = blend(term[3], primary, 0.30)
    syntax_special = blend(tertiary, primary, 0.30)
    syntax_specialchar = blend(tertiary, primary, 0.30)
    syntax_tag = blend(primary, primary, 0.30)
    syntax_delimiter = blend(on_surface_variant, primary, 0.30)
    syntax_specialcomment = blend(outline, primary, 0.45)
    syntax_debug = blend(error, primary, 0.30)
    syntax_underlined = blend(primary, primary, 0.30)
    syntax_ignore = blend(outline, primary, 0.30)
    syntax_todo = blend(tertiary, primary, 0.30)

    mapping = {
        "background_mode": background_mode,
        "primary": primary,
        "on_primary": on_primary,
        "primary_container": primary_container,
        "on_primary_container": on_primary_container,
        "secondary": secondary,
        "tertiary": tertiary,
        "surface": surface,
        "surface_dim": surface_dim,
        "surface_container": surface_container,
        "surface_container_low": surface_container_low,
        "surface_container_high": surface_container_high,
        "on_surface": on_surface,
        "on_surface_variant": on_surface_variant,
        "outline": outline,
        "outline_variant": outline_variant,
        "error": error,
        # Syntax colors with 30% primary blend
        "syntax_comment": syntax_comment,
        "syntax_constant": syntax_constant,
        "syntax_string": syntax_string,
        "syntax_character": syntax_character,
        "syntax_number": syntax_number,
        "syntax_boolean": syntax_boolean,
        "syntax_float": syntax_float,
        "syntax_identifier": syntax_identifier,
        "syntax_function": syntax_function,
        "syntax_statement": syntax_statement,
        "syntax_conditional": syntax_conditional,
        "syntax_repeat": syntax_repeat,
        "syntax_label": syntax_label,
        "syntax_operator": syntax_operator,
        "syntax_keyword": syntax_keyword,
        "syntax_exception": syntax_exception,
        "syntax_preproc": syntax_preproc,
        "syntax_include": syntax_include,
        "syntax_define": syntax_define,
        "syntax_macro": syntax_macro,
        "syntax_precondit": syntax_precondit,
        "syntax_type": syntax_type,
        "syntax_storageclass": syntax_storageclass,
        "syntax_structure": syntax_structure,
        "syntax_typedef": syntax_typedef,
        "syntax_special": syntax_special,
        "syntax_specialchar": syntax_specialchar,
        "syntax_tag": syntax_tag,
        "syntax_delimiter": syntax_delimiter,
        "syntax_specialcomment": syntax_specialcomment,
        "syntax_debug": syntax_debug,
        "syntax_underlined": syntax_underlined,
        "syntax_ignore": syntax_ignore,
        "syntax_todo": syntax_todo,
        **{f"term{i}": term[i] for i in range(16)},
    }

    content = VIM_TEMPLATE.format(**mapping)

    if output_dir is None:
        output_dir = os.path.expanduser("~/.config/nvim/colors")

    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "iNiR.vim")
    with open(output_path, "w") as f:
        f.write(content)

    return output_path


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    if len(sys.argv) < 2:
        scss_path = os.path.expanduser(
            "~/.local/state/quickshell/user/generated/material_colors.scss"
        )
    else:
        scss_path = sys.argv[1]

    if not os.path.exists(scss_path):
        print(f"Error: {scss_path} not found", file=sys.stderr)
        sys.exit(1)

    output = generate_neovim_theme(scss_path)
    print(f"[neovim] Colorscheme written: {output}")

    # Auto-integrate into init.vim / init.lua
    nvim_config = os.path.expanduser("~/.config/nvim")
    status = ensure_nvim_integration(nvim_config)
    print(f"[neovim] Init config: {status}")

    # Reload running Neovim instances
    reload_neovim()
