#!/usr/bin/env bash
# Auto-generated from QML IpcHandler declarations + docs/IPC.md metadata.
# Do not edit manually.
# Regenerate: python3 scripts/lib/generate-ipc-registry.py
# IPC.md hash: f3dd1f8bcde8479a
# Targets: 45

declare -gA IPC_TARGET_DESC=(
  [ai]="AI chat service. Multi-provider (Gemini, OpenAI, Mistral) with tool support."
  [altSwitcher]="Alt+Tab window switcher. Works across workspaces, unlike some other implementations we won't name."
  [appCatalog]="App catalog service. Browse, search, and install curated applications."
  [audio]="Volume and mute control."
  [bar]="Top bar visibility."
  [brightness]="Display brightness control."
  [cheatsheet]="Keyboard shortcuts reference. For when you forget what you just configured five minutes ago."
  [clipboard]="Clipboard history panel. Because Ctrl+V only remembers one thing, and that's not enough for power users."
  [cliphistService]="Clipboard history service. The backend that makes clipboard panel work. You probably don't need to call this directly."
  [closeConfirm]="Close window confirmation dialog. Shows a prompt before closing the focused window. Useful if you're the type who accidentally closes things and then regrets it."
  [controlPanel]="Quick settings panel. Toggles, sliders, and system controls without opening full settings."
  [coverflowSelector]="Wallpaper coverflow (3D card) picker."
  [gamemode]="Performance mode for gaming. Auto-detects fullscreen apps and disables animations/effects. Can also be toggled manually for those stubborn games that don't go fullscreen properly."
  [globalActions]="Command palette / action registry. Search and execute shell actions from scripts or keybinds."
  [keyboard]="Keyboard layout switching (Niri only). Cycles through configured keyboard layouts and queries layout info."
  [lock]="Lock screen. For when you need to pretend you're working."
  [mediaControls]="Floating media controls panel."
  [minimize]="Window minimization (Niri workaround - moves windows to hidden workspace)."
  [mpris]="Media player control. Automatically detects and uses YtMusic controls when active, otherwise uses the active MPRIS player."
  [notifications]="Notification management."
  [osd]="Waffle on-screen display indicator (volume, brightness)."
  [osdVolume]="On-screen volume indicator."
  [osk]="On-screen keyboard."
  [overlay]="The central overlay. Search, quick actions, widgets. The thing that pops up and makes you feel productive."
  [overview]="Toggle the workspace overview panel. The one with all your windows looking tiny and organized."
  [packageSearch]="Package search service. Searches pacman repos and installed packages."
  [panelFamily]="Switch between panel styles. ii supports two visual styles: Material ii (default) and Waffle (Windows 11-like)."
  [region]="Region selection tools. Screenshots, OCR, recording. Draw a box, get stuff done."
  [search]="Waffle start menu / search."
  [session]="Power menu. Logout, suspend, reboot, shutdown. The \"I'm done for today\" buttons."
  [settings]="Open the settings window. GUI config so you don't have to edit JSON like it's 2005."
  [shellUpdate]="Shell update checker. Monitors the git repo for new commits and shows an update overlay."
  [sidebarLeft]="Left sidebar (AI chat, apps)."
  [sidebarRight]="Right sidebar (quick toggles, notepad, settings)."
  [taskview]="Waffle task view (Win+Tab style)."
  [tiling]="Tiling layout overlay. Pick or cycle through tiling presets for the current workspace."
  [voiceSearch]="Voice search using Gemini API. Records from microphone, transcribes with Gemini, opens Google search."
  [wactionCenter]="Waffle action center (quick settings)."
  [waffleAltSwitcher]="Waffle Alt+Tab window switcher. Separate from the ii \`altSwitcher\` — supports quick-switch (first tab switches instantly, second opens UI) and no-visual-UI mode."
  [wallpaperSelector]="Wallpaper picker grid."
  [wbar]="Waffle taskbar visibility."
  [wnotificationCenter]="Waffle notification center."
  [wwidgets]="Waffle widgets panel."
  [ytmusic]="Direct YtMusic player control. Use these if you want to control YtMusic specifically, regardless of what other players are active."
  [zoom]="Screen zoom. Accessibility feature, or for reading tiny text without squinting."
)

declare -gA IPC_TARGET_FAMILY=(
  [ai]="shared"
  [altSwitcher]="shared"
  [appCatalog]="shared"
  [audio]="shared"
  [bar]="shared"
  [brightness]="shared"
  [cheatsheet]="shared"
  [clipboard]="shared"
  [cliphistService]="shared"
  [closeConfirm]="shared"
  [controlPanel]="shared"
  [coverflowSelector]="shared"
  [gamemode]="shared"
  [globalActions]="shared"
  [keyboard]="shared"
  [lock]="shared"
  [mediaControls]="shared"
  [minimize]="shared"
  [mpris]="shared"
  [notifications]="shared"
  [osd]="waffle"
  [osdVolume]="shared"
  [osk]="shared"
  [overlay]="ii"
  [overview]="shared"
  [packageSearch]="shared"
  [panelFamily]="shared"
  [region]="shared"
  [search]="waffle"
  [session]="shared"
  [settings]="shared"
  [shellUpdate]="shared"
  [sidebarLeft]="shared"
  [sidebarRight]="shared"
  [taskview]="waffle"
  [tiling]="shared"
  [voiceSearch]="shared"
  [wactionCenter]="waffle"
  [waffleAltSwitcher]="waffle"
  [wallpaperSelector]="shared"
  [wbar]="waffle"
  [wnotificationCenter]="waffle"
  [wwidgets]="waffle"
  [ytmusic]="shared"
  [zoom]="shared"
)

declare -gA IPC_TARGET_FUNCTIONS=(
  [ai]="ensureInitialized diagnose run runGet"
  [altSwitcher]="open close toggle next previous"
  [appCatalog]="refresh search install list"
  [audio]="volumeUp volumeDown mute micMute"
  [bar]="toggle close open"
  [brightness]="increment decrement"
  [cheatsheet]="toggle close open"
  [clipboard]="open close toggle"
  [cliphistService]="update"
  [closeConfirm]="trigger close"
  [controlPanel]="toggle close open"
  [coverflowSelector]="toggle open close"
  [gamemode]="toggle activate deactivate status"
  [globalActions]="run list search open"
  [keyboard]="switchLayout switchLayoutPrevious getCurrentLayout getLayouts"
  [lock]="activate deactivate status focus"
  [mediaControls]="toggle close open"
  [minimize]="minimize restore"
  [mpris]="pauseAll playPause previous next"
  [notifications]="test clearAll toggleSilent"
  [osd]="trigger"
  [osdVolume]="trigger hide toggle"
  [osk]="toggle close open"
  [overlay]="toggle"
  [overview]="toggle close open toggleReleaseInterrupt clipboardToggle actionOpen"
  [packageSearch]="search results"
  [panelFamily]="cycle set"
  [region]="screenshot search googleLens ocr record recordWithSound"
  [search]="toggle close open"
  [session]="toggle close open"
  [settings]="open toggle"
  [shellUpdate]="toggle open close check performUpdate dismiss undismiss diagnose"
  [sidebarLeft]="toggle close open"
  [sidebarRight]="toggle close open"
  [taskview]="toggle close open"
  [tiling]="toggle open hide cycle showOsd promote"
  [voiceSearch]="start stop toggle"
  [wactionCenter]="toggle"
  [waffleAltSwitcher]="open close toggle next previous"
  [wallpaperSelector]="toggle open close toggleOnMonitor random"
  [wbar]="toggle close open"
  [wnotificationCenter]="toggle"
  [wwidgets]="toggle close open"
  [ytmusic]="playPause next previous stop"
  [zoom]="zoomIn zoomOut"
)

declare -gA IPC_FUNCTION_DESC=(
  ["ai:ensureInitialized"]="Force-load models and API keys"
  ["ai:diagnose"]="Dump current AI state (model, keys, config) as JSON"
  ["ai:run"]="Send a message or \`/command\` to the AI chat"
  ["ai:runGet"]="Run AI command and return the last response"
  ["altSwitcher:open"]="Open switcher"
  ["altSwitcher:close"]="Close switcher"
  ["altSwitcher:toggle"]="Toggle switcher"
  ["altSwitcher:next"]="Focus next window"
  ["altSwitcher:previous"]="Focus previous window"
  ["appCatalog:refresh"]="Refresh the installed-state cache"
  ["appCatalog:search"]="Filter catalog entries by query"
  ["appCatalog:install"]="Install app by catalog ID"
  ["appCatalog:list"]="List catalog apps with install status and descriptions"
  ["audio:volumeUp"]="Increase volume"
  ["audio:volumeDown"]="Decrease volume"
  ["audio:mute"]="Toggle speaker mute"
  ["audio:micMute"]="Toggle microphone mute"
  ["bar:toggle"]="Show/hide bar"
  ["bar:close"]="Hide bar"
  ["bar:open"]="Show bar"
  ["brightness:increment"]="Increase brightness"
  ["brightness:decrement"]="Decrease brightness"
  ["cheatsheet:toggle"]="Open/close cheatsheet"
  ["cheatsheet:close"]="Hide cheatsheet overlay"
  ["cheatsheet:open"]="Show cheatsheet overlay"
  ["clipboard:open"]="Open panel"
  ["clipboard:close"]="Close panel"
  ["clipboard:toggle"]="Open/close panel"
  ["cliphistService:update"]="Refresh clipboard history"
  ["closeConfirm:trigger"]="Show close confirmation for focused window"
  ["closeConfirm:close"]="Dismiss the dialog without closing"
  ["controlPanel:toggle"]="Open/close control panel"
  ["controlPanel:close"]="Close control panel"
  ["controlPanel:open"]="Open control panel"
  ["coverflowSelector:toggle"]="Open/close coverflow selector"
  ["coverflowSelector:open"]="Open coverflow selector"
  ["coverflowSelector:close"]="Close coverflow selector"
  ["gamemode:toggle"]="Toggle gamemode on/off"
  ["gamemode:activate"]="Force enable gamemode"
  ["gamemode:deactivate"]="Force disable gamemode"
  ["gamemode:status"]="Print current gamemode state (e.g. \`active (manual)\`, \`inactive (off)\`)"
  ["globalActions:run"]="Execute action by ID (e.g. \`toggle-mute\`, \`install-package vim\`)"
  ["globalActions:list"]="List all actions, optionally filtered by category"
  ["globalActions:search"]="Fuzzy search actions by name/description/keywords"
  ["globalActions:open"]="Open the overview in action mode"
  ["keyboard:switchLayout"]="Switch to next keyboard layout"
  ["keyboard:switchLayoutPrevious"]="Switch to previous keyboard layout"
  ["keyboard:getCurrentLayout"]="Get the current layout name"
  ["keyboard:getLayouts"]="Get all configured layout names (JSON array)"
  ["lock:activate"]="Lock the screen"
  ["lock:deactivate"]="Cancel lock and mark screen unlocked"
  ["lock:status"]="Return lock state (\`locked\`, \`activating\`, or \`unlocked\`)"
  ["lock:focus"]="Refocus the lock screen input"
  ["mediaControls:toggle"]="Open/close media controls"
  ["mediaControls:close"]="Hide media controls"
  ["mediaControls:open"]="Show media controls"
  ["minimize:minimize"]="Minimize focused window"
  ["minimize:restore"]="Restore a minimized window by ID"
  ["mpris:pauseAll"]="Pause all players"
  ["mpris:playPause"]="Toggle play/pause (uses YtMusic if active)"
  ["mpris:previous"]="Previous track (uses YtMusic if active)"
  ["mpris:next"]="Next track (uses YtMusic if active)"
  ["notifications:test"]="Send test notifications"
  ["notifications:clearAll"]="Dismiss all notifications"
  ["notifications:toggleSilent"]="Toggle Do Not Disturb mode"
  ["osd:trigger"]="Show the OSD indicator"
  ["osdVolume:trigger"]="Show volume OSD"
  ["osdVolume:hide"]="Hide volume OSD"
  ["osdVolume:toggle"]="Toggle volume OSD"
  ["osk:toggle"]="Show/hide on-screen keyboard"
  ["osk:close"]="Hide on-screen keyboard"
  ["osk:open"]="Show on-screen keyboard"
  ["overlay:toggle"]="Open/close overlay"
  ["overview:toggle"]="Open/close overview"
  ["overview:close"]="Close overview"
  ["overview:open"]="Open overview"
  ["overview:toggleReleaseInterrupt"]="Clear the super-key release interrupt flag"
  ["overview:clipboardToggle"]="Open clipboard search, or close if already open"
  ["overview:actionOpen"]="Open overview in action search mode"
  ["packageSearch:search"]="Start a package search"
  ["packageSearch:results"]="Print current search results"
  ["panelFamily:cycle"]="Cycle to next panel family (ii → waffle → ii)"
  ["panelFamily:set"]="Set specific family (\"ii\" or \"waffle\")"
  ["region:screenshot"]="Take a region screenshot"
  ["region:search"]="Image search (Google Lens)"
  ["region:googleLens"]="Start a region capture for Google Lens"
  ["region:ocr"]="OCR text recognition"
  ["region:record"]="Record region (no audio)"
  ["region:recordWithSound"]="Record region with audio"
  ["search:toggle"]="Open/close start menu"
  ["search:close"]="Close start menu"
  ["search:open"]="Open start menu"
  ["session:toggle"]="Open/close session menu"
  ["session:close"]="Hide session screen"
  ["session:open"]="Show session screen"
  ["settings:open"]="Open settings window"
  ["settings:toggle"]="Toggle settings (overlay mode toggles, window mode opens)"
  ["shellUpdate:toggle"]="Open/close update overlay"
  ["shellUpdate:open"]="Open update overlay"
  ["shellUpdate:close"]="Close update overlay"
  ["shellUpdate:check"]="Check for updates now"
  ["shellUpdate:performUpdate"]="Run the update"
  ["shellUpdate:dismiss"]="Dismiss update notification"
  ["shellUpdate:undismiss"]="Un-dismiss update notification"
  ["shellUpdate:diagnose"]="Dump update state as JSON"
  ["sidebarLeft:toggle"]="Open/close left sidebar"
  ["sidebarLeft:close"]="Hide left sidebar"
  ["sidebarLeft:open"]="Show left sidebar"
  ["sidebarRight:toggle"]="Open/close right sidebar"
  ["sidebarRight:close"]="Hide right sidebar"
  ["sidebarRight:open"]="Show right sidebar"
  ["taskview:toggle"]="Open/close task view"
  ["taskview:close"]="Hide task view"
  ["taskview:open"]="Show task view"
  ["tiling:toggle"]="Open/close tiling picker"
  ["tiling:open"]="Open tiling picker"
  ["tiling:hide"]="Close picker and OSD"
  ["tiling:cycle"]="Cycle to next tiling preset (shows OSD)"
  ["tiling:showOsd"]="Flash the current tiling preset OSD"
  ["tiling:promote"]="Promote focused window to master position"
  ["voiceSearch:start"]="Start recording"
  ["voiceSearch:stop"]="Stop recording"
  ["voiceSearch:toggle"]="Toggle recording"
  ["wactionCenter:toggle"]="Open/close action center"
  ["waffleAltSwitcher:open"]="Open switcher"
  ["waffleAltSwitcher:close"]="Close switcher"
  ["waffleAltSwitcher:toggle"]="Toggle switcher"
  ["waffleAltSwitcher:next"]="Focus next window"
  ["waffleAltSwitcher:previous"]="Focus previous window"
  ["wallpaperSelector:toggle"]="Open/close wallpaper selector"
  ["wallpaperSelector:open"]="Open wallpaper selector"
  ["wallpaperSelector:close"]="Close wallpaper selector"
  ["wallpaperSelector:toggleOnMonitor"]="Open wallpaper selector on a specific monitor"
  ["wallpaperSelector:random"]="Pick a random wallpaper from the current folder"
  ["wbar:toggle"]="Show/hide taskbar"
  ["wbar:close"]="Hide taskbar"
  ["wbar:open"]="Show taskbar"
  ["wnotificationCenter:toggle"]="Open/close notification center"
  ["wwidgets:toggle"]="Open/close widgets"
  ["wwidgets:close"]="Close widgets"
  ["wwidgets:open"]="Open widgets"
  ["ytmusic:playPause"]="Toggle YtMusic play/pause"
  ["ytmusic:next"]="Play next track in YtMusic"
  ["ytmusic:previous"]="Play previous track in YtMusic"
  ["ytmusic:stop"]="Stop YtMusic playback"
  ["zoom:zoomIn"]="Increase zoom level"
  ["zoom:zoomOut"]="Decrease zoom level"
)

declare -gA IPC_FUNCTION_ARGS=(
  ["ai:run"]="<inputText>"
  ["ai:runGet"]="<inputText>"
  ["appCatalog:search"]="<query>"
  ["appCatalog:install"]="<id>"
  ["globalActions:run"]="<actionId> <args>"
  ["globalActions:list"]="<category>"
  ["globalActions:search"]="<query>"
  ["minimize:restore"]="<windowId>"
  ["packageSearch:search"]="<query>"
  ["panelFamily:set"]="<family>"
  ["wallpaperSelector:toggleOnMonitor"]="<monitorName>"
)

declare -gA IPC_TARGET_EXAMPLE=(
  [altSwitcher]='bind "Alt+Tab" { spawn "inir" "altSwitcher" "next"; }
bind "Alt+Shift+Tab" { spawn "inir" "altSwitcher" "previous"; }'
  [cheatsheet]='bind "Super+Slash" { spawn "inir" "cheatsheet" "toggle"; }'
  [clipboard]='bind "Super+V" { spawn "inir" "clipboard" "toggle"; }'
  [closeConfirm]='bind "Mod+Q" repeat=false { spawn "inir" "close-window"; }'
  [gamemode]='bind "Super+F12" { spawn "inir" "gamemode" "toggle"; }'
  [globalActions]='bind "Super+Slash" { spawn "inir" "globalActions" "open"; }
bind "Super+M" { spawn "inir" "globalActions" "run" "toggle-mute"; }'
  [keyboard]='bind "Mod+Alt+K" { spawn "inir" "keyboard" "switchLayout"; }'
  [lock]='bind "Super+Alt+L" allow-when-locked=true { spawn "inir" "lock" "activate"; }'
  [mpris]='bind "Ctrl+Mod+Space" { spawn "inir" "mpris" "playPause"; }
bind "Mod+Alt+N" { spawn "inir" "mpris" "next"; }
bind "Mod+Alt+P" { spawn "inir" "mpris" "previous"; }'
  [overlay]='bind "Super+G" { spawn "inir" "overlay" "toggle"; }'
  [overview]='bind "Mod+Space" { spawn "inir" "overview" "toggle"; }'
  [panelFamily]='bind "Mod+Shift+W" { spawn "inir" "panelFamily" "cycle"; }'
  [region]='bind "Super+Shift+S" { spawn "inir" "region" "screenshot"; }
bind "Super+Shift+X" { spawn "inir" "region" "ocr"; }
bind "Super+Shift+A" { spawn "inir" "region" "search"; }'
  [session]='bind "Super+Shift+E" { spawn "inir" "session" "toggle"; }'
  [settings]='bind "Super+Comma" { spawn "inir" "settings"; }'
  [voiceSearch]='bind "Super+Shift+V" { spawn "inir" "voiceSearch" "toggle"; }'
  [wallpaperSelector]='bind "Ctrl+Alt+T" { spawn "inir" "wallpaperSelector" "toggle"; }'
  [ytmusic]='bind "Mod+M+Space" { spawn "inir" "ytmusic" "playPause"; }'
)

IPC_ALL_TARGETS=(ai altSwitcher appCatalog audio bar brightness cheatsheet clipboard cliphistService closeConfirm controlPanel coverflowSelector gamemode globalActions keyboard lock mediaControls minimize mpris notifications osd osdVolume osk overlay overview packageSearch panelFamily region search session settings shellUpdate sidebarLeft sidebarRight taskview tiling voiceSearch wactionCenter waffleAltSwitcher wallpaperSelector wbar wnotificationCenter wwidgets ytmusic zoom)
IPC_SHARED_TARGETS=(ai altSwitcher appCatalog audio bar brightness cheatsheet clipboard cliphistService closeConfirm controlPanel coverflowSelector gamemode globalActions keyboard lock mediaControls minimize mpris notifications osdVolume osk overview packageSearch panelFamily region session settings shellUpdate sidebarLeft sidebarRight tiling voiceSearch wallpaperSelector ytmusic zoom)
IPC_II_TARGETS=(overlay)
IPC_WAFFLE_TARGETS=(osd search taskview wactionCenter waffleAltSwitcher wbar wnotificationCenter wwidgets)

declare -gA IPC_KEBAB_ALIASES=(
  [alt-switcher]=altSwitcher
  [app-catalog]=appCatalog
  [cliphist-service]=cliphistService
  [close-confirm]=closeConfirm
  [control-panel]=controlPanel
  [coverflow-selector]=coverflowSelector
  [global-actions]=globalActions
  [media-controls]=mediaControls
  [osd-volume]=osdVolume
  [package-search]=packageSearch
  [panel-family]=panelFamily
  [shell-update]=shellUpdate
  [sidebar-left]=sidebarLeft
  [sidebar-right]=sidebarRight
  [voice-search]=voiceSearch
  [waction-center]=wactionCenter
  [waffle-alt-switcher]=waffleAltSwitcher
  [wallpaper-selector]=wallpaperSelector
  [wnotification-center]=wnotificationCenter
)

